### ISSUE TITLE
Record Alexa Responses for re-testing an utterance

### ISSUE THREAD

**Issue by lukeluneau** [alexa/ask-cli#109]
I want to track how my skill responds to changes, so it would be helpful for the skill to track the utterance/response pairs

**Comment by RonWang** [comment]
Hey @lukeluneau , I feel your requirement is very similar to https://github.com/alexa/ask-cli/issues/56, could you please check if the original `ask dialog --output` is the feature you are thinking of? You can also check the doc for this command at https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference-v1.html#dialog-command. Let me know how do you think!

**Comment by RonWang** [comment]
Close this issue because of the inactivity in this thread. Please feel free to reopen if you still have relative questions. We will also consider how to better show the key request-response in the current ask-cli.
