### ISSUE TITLE
get-task / search-task now missing in the new SDK

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#114]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It seems the functionality to get-tasks and list-tasks is now gone.
https://github.com/alexa/ask-cli/blob/984d37b9f7abfb651b2737a71c46accb9dd78dce/lib/utils/constants.js#L349
Please bring it back via the smapi subcommand.
Otherwise this documentation on tasks is inaccurate:
https://developer.amazon.com/en-US/docs/alexa/custom-skills/implement-custom-tasks-in-your-skill.html#how-can-skill-developers-see-my-task

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
PR is open https://github.com/alexa/ask-cli/pull/150

**Comment by kakhaUrigashvili** [comment]
fixed released in version 2.3.0
