### ISSUE TITLE
Creating a new self-hosted skill fails with TypeError

### ISSUE THREAD

**Issue by sleb** [alexa/ask-cli#115]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

A new self-hosted skill package is created

## Current Behavior

CLI fails with TypeError

**CLI Snapshot**

![image](https://user-images.githubusercontent.com/2142392/79055842-0a6fc800-7c05-11ea-9ba2-badef1ac7cdb.png)

## Steps to Reproduce (for bugs)

1. run `ask new`
2. choose `Java`
3. choose `self-hosted and manage your own hosting`
4. error: `[Error]: TypeError: Cannot read property 'NAME' of undefined`

## Your Environment and Context

* ask-cli version: 2.0.1
* Operating System and version: macOS Catalina 10.15.4
* Node.js version used for development: v13.12.0
* NPM version used for development: 6.14.4

**Comment by RonWang** [comment]
This is now resolved by release v2.1.0 https://github.com/alexa/ask-cli/releases/tag/v2.1.0
