### ISSUE TITLE
"TypeError: cb is not a function" after deployment of lambda function

### ISSUE THREAD

**Issue by JoJ123** [alexa/ask-cli#116]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
`ask deploy` without any error

## Current Behavior
`ask deploy` deploys the lambda function to aws.
At the end of the run it displays a Type Error.

**CLI Snapshot**
![image](https://user-images.githubusercontent.com/38938791/79071564-c223d900-7cdc-11ea-958e-ac777d160259.png)

## Your Environment and Context

* ask-cli version: 2.0.1
* Operating System and version: Windows 10
* Node.js version used for development: 12.16.1
* NPM version used for development: 6.13.4

**Comment by JoJ123** [comment]
This issue can be solved with:
https://github.com/alexa/ask-cli/issues/59#issuecomment-595696297

Maybe you can add this to the README
I spend a lot of time too find this solution

**Comment by RonWang** [comment]
Hey @JoJ123 ,

Thanks for your reports! I definitely get your issue from this issue https://github.com/alexa/ask-cli/issues/117, but could you explain a little why this issue is related to the powershell's Compress-Archive command?

Thanks,
Ron

**Comment by RonWang** [comment]
Actually the `cb is not a function` is displayed, because I noticed you are running the command as **ask deploy target lambda**. The misusage here is that the target is removed already in v2 deploy command, as CLI can automatically detect which resource needs the deploy.

We just sent a PR to address the "cb" problem. https://github.com/alexa/ask-cli/pull/130

**Comment by JoJ123** [comment]
@RonWang 
I wanted to start again from scratch to reproduce this issue.

It happened also directly on the `ask new`
![image](https://user-images.githubusercontent.com/38938791/79632387-1dcbe780-815f-11ea-8075-24869df8761d.png)

**Comment by RonWang** [comment]
@JoJ123 Please check the latest version of ask-cli v2.1.1, the "cb is not a function" issue is solved in the commit https://github.com/alexa/ask-cli/commit/3e2698a626f6607c818d697d9ce987823462576c.
