### ISSUE TITLE
ask new (NodeJS, AWS Lambda, Hello World) --> Module Error

### ISSUE THREAD

**Issue by JoJ123** [alexa/ask-cli#117]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Sample Project is not useable

## Expected Behavior
Hello World example is startable.

## Current Behavior

After deploying the skill I wanted to test it with the skill tester. Empty response.
So I've checked the lambda function directly and tried to run the function with a test.
After few seconds the test fails with the error message:
`Module not found: GenericErrorMapper`
`"errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module './dispatcher/error/mapper/GenericErrorMapper'",`

**CLI Snapshot**
![image](https://user-images.githubusercontent.com/38938791/79076112-ac6fdd00-7cf7-11ea-95be-9b129b0b853b.png)

## Steps to Reproduce (for bugs)

`ask new`
Selection: NodeJS, AWS Lambda, Hello World
`ask deploy`
Test your skill

## Possible Solution
I tried to run the generated index.js locally:
![image](https://user-images.githubusercontent.com/38938791/79076121-c14c7080-7cf7-11ea-875f-33cab76f0dfd.png)
There it's working fine:
![image](https://user-images.githubusercontent.com/38938791/79076094-a2e67500-7cf7-11ea-9141-971cbaee4f04.png)

## Your Environment and Context

* ask-cli version: 2.0.1
* Operating System and version: Windows 10
* Node.js version used for development: 12.16.1
* NPM version used for development: 6.13.4

**Comment by JoJ123** [comment]
This issue can be solved with:
https://github.com/alexa/ask-cli/issues/59#issuecomment-595696297

Maybe you can add this to the README
I spend a lot of time too find this solution

**Comment by Whobeu** [comment]
I had not created a new Skill in a long time. Just maintaining and updating existing Skills. Decided to create a new Skill and updated to ask-cli 2.x.x. Whoa. The whole layout is changed AND I ran into this bug. Followed the instructions in command #59 and it appears to be working now.

**Comment by RonWang** [comment]
Hi @JoJ123 and @Whobeu , sorry this issue is happening... and I was hoping Windows can update the default Powershell PSGallery to avoid using the broken version someday in the future... 

That said, we update our [FAQ](https://github.com/alexa/ask-cli/blob/develop/docs/FAQ.md#q-for-windows-users-if-your-skill-return-empty-response-and-log-shows-module-not-found-genericerrormapper-or-cannot-find-module-dispatchererrormappergenericerrormapper-how-to-resolve) to reflect this Powershell problem. Hope this helps!
