### ISSUE TITLE
Unable to deploy new project from custom template

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#118]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When creating a new project with `ask new`, I can set the invocation name and then immediately do `ask deploy` with no issues. I expect the same when creating a new project using a custom template specified by `--template-url`, assuming that the custom template is compatible with the official templates.

## Current Behavior
When I use `--template-url` to specify a custom template (or even a direct fork of the official hello world template with no changes), `ask deploy` fails with:

```
[Error]: {
  "message": "Skill is not ready for enablement.",
  "violations": [
    {
      "code": "MISSING_REQUIRED_PROPERTY",
      "message": "Object instance at property path \"$.manifest.apis.custom\" has missing required property: \"endpoint\".",
      "validationDetails": {
        "originalInstance": {
          "propertyPath": "$.manifest.apis.custom",
          "type": "BODY"
        },
        "requiredProperty": "endpoint"
      }
    }
  ]
}
```

I can make it work by recreating the `infrastructure/lambda-deployer` folder and tweaking `ask-resources.json` to include the AWS region and "type" property. 

What's more, I notice that projects created with `ask new` will have their `.git` folder deleted, but those created with a custom template do not. That leads me to believe that the reason might be because when `--template-url` is set, the lines at https://github.com/alexa/ask-cli/blob/develop/lib/commands/new/index.js#L100-L102 return out of `createNonHostedSkill()` before the work can be done in the lines that follow to delete `.git` and setup the rest of the project.
## Steps to Reproduce (for bugs)
Create a fork of https://github.com/alexa/skill-sample-nodejs-hello-world and then use the fork's URL with `ask new --template-url` to create a new project. Observe that `.git` is not deleted, `infrastructure/lambda-deployer` is missing, and `ask-resources.json` is missing a few lines compared to what you would get with `ask new`. When doing `ask deploy`, it will fail as described above.

## Your Environment and Context
* ask-cli version: 2.0.1
* Operating System and version: MacOS 10.15.2
* Node.js version used for development: 12.16.2
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
fixed in 2.2.0
