### ISSUE TITLE
v2 ask-cli misses "ask util generate-lwa-tokens" command

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#119]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Expect I can generate LWA token using command `ask util generate-lwa-tokens`.

## Current Behavior

The command does not exist.

## Your Environment and Context

* ask-cli version: 2.0.1

**Comment by nikhilym** [comment]
This documentation https://developer.amazon.com/en-US/docs/alexa/smapi/get-access-token-smapi.html also needs to be updated, as pointed out [here](https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/144).

**Comment by RonWang** [comment]
Fix to the issue is sent to PR now https://github.com/alexa/ask-cli/pull/120

**Comment by nikhilym** [comment]
Appreciate the quick PR @RonWang !!

**Comment by RonWang** [comment]
PR checked-in, waiting for next release

**Comment by RonWang** [comment]
This is now resolved by release v2.1.0 https://github.com/alexa/ask-cli/releases/tag/v2.1.0
