### ISSUE TITLE
ASK CLI v2: Provide account linking info as file

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#133]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

WIth ASK CLI v1, you could submit account linking information with `ask api create-account-linking`, providing only the skill ID and a filename of the JSON file containing the account linking information. This was very simple and straightforward and I'd like to see this in ASK CLI v2.

## Current Behavior
ASK CLI v2 *does* support the creation and update of account linking information via `ask smapi update-account-linking-info`, but it requires the stage in addition to the skill ID and JSON. Furthermore, the JSON must be presented on the command line as a string and I see no way to submit it as a file (at least not without some clever shell scripting to flatten the file into a string). 

I'd prefer that the `--stage` parameter be optional and default to "development". But even then I can live with that if there were a way (without shell scripting help) to provide the JSON from a file instead of JSON as the value of the `--account-linking-request` parameter. 

**CLI Snapshot**
For example, compare this CLI usage from ASK CLI v1...

```
$ ask api create-account-linking --skill-id amzn1.ask.skill.some-skill-id --file=linking.json
```

...with this for ASK CLI v2...

```
$ ask smapi update-account-linking-info --skill-id amzn1.ask.skill.some-skill-id --stage development --account-linking-request '{"accountLinkingRequest": {"clientId": "someclient","clientSecret": "somesecret","skipOnEnablement": true,"type": "AUTH_CODE","authorizationUrl": "https://someservice.com/oauth2/auth","domains": [],"scopes": ["somescope", "someotherscope"],"accessTokenUrl": "https://someservice/oauth2/token","accessTokenScheme": "HTTP_BASIC"}}'
```

## Steps to Reproduce (for bugs)
See above...

## Possible Solution
See above...

## Your Environment and Context

* ask-cli version: 2.1.0
* Operating System and version: MacOS 10.15.2
* Node.js version used for development: 12.16.2
* NPM version used for development: 6.14.4

**Comment by habuma** [comment]
FWIW, after submitting this I saw #132. (I had started creating this issue hours before #132 was created and didn't submit mine until after it was created, so...I missed it.)

I get that `cat` (or `type` for Windows) will work, but it's still much more complicated than it was with ASK CLI v1.

**Comment by kakhaUrigashvili** [comment]
@habuma I am going to close this one since it is the same request as https://github.com/alexa/ask-cli/issues/132. Please track progress on https://github.com/alexa/ask-cli/issues/132
