### ISSUE TITLE
fatal: Remote branch ask-cli-x not found in upstream origin

### ISSUE THREAD

**Issue by nguyendat** [alexa/ask-cli#137]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Able to create new skill from template-url

## Current Behavior

**CLI Snapshot**

## Steps to Reproduce (for bugs)

Run command to clone template:
ask new -p linus --template-url https://github.com/linuxacademy/content-aws-skill-builder.git
<img width="894" alt="Screen Shot 2020-04-21 at 8 53 39 AM" src="https://user-images.githubusercontent.com/468344/79816526-aa6be500-83ad-11ea-9f0f-dc9688944fac.png">

## Your Environment and Context

* ask-cli version: 2.1.1
* Operating System and version:
* Node.js version used for development: v12.16.2
* NPM version used for development: 6.14.4

**Comment by RonWang** [comment]
Hey @nguyendat , 

First, it seems the template that you wish to new with is still using v1 structure of the codebase... (if you look at https://github.com/linuxacademy/content-aws-skill-builder)

V2 CLI has updated its supported project structure with the format mentioned in https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Alexa-Skill-Project-Definition.md now. 

In another angle, is https://github.com/alexa/ask-cli/issues/40 also the feature that you are looking for?

**Comment by nguyendat** [comment]
Thanks @RonWang, it seem references repos using out of date format. Thanks for mention #40 👍
