### ISSUE TITLE
ASK_REFRESH_TOKEN Not working in v1 and v2

### ISSUE THREAD

**Issue by xavidop** [alexa/ask-cli#144]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The CLI with ASK_REFRESH_TOKEN is not working in CLI v1 and CLI v2

## Expected Behavior
It should refresh the token when the tokes has expired

## Current Behavior
I am deploying using environment variables. I have tested setting ASK_ACCES_TOKEN, ASK_VENDOR_ID, AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

When I set these variables and also add the profile __ENVIRONMENT_ASK_PROFILE__ in ./ask/config works both in cli v1.7.23 and v2.1.1 and it seems to be ok. But the problem is when I set the variable ASK_REFRESH_TOKEN in order to have that token to automatically refresh the access token when I am using envirnmonent variables.

The problem is that in CLI v1 when I set this variable, I get the error: 

-------------------- Update Skill Project --------------------
  -  skill status checking...Error: Bad Request
Failed to refresh access token.

the .ask/config in v1 is:

`{
  "deploy_settings": {
    "default": {
      "skill_id": "amzn1.ask.skill.ed038d5e-61eb-4383-a480-04e3398b398d",
      "was_cloned": false,
      "merge": {},
      "resources": {
        "manifest": {
          "eTag": "689365afa95f4182154f2b7af78f6072"
        },
        "interactionModel": {
          "es-ES": {
            "eTag": "7f2f7bea2c1a6fe426e79007d7cf1798"
          }
        },
        "lambda": [
          {
            "alexaUsage": [
              "custom/default"
            ],
            "arn": "arn:aws:lambda:us-east-1:141568529918:function:ask-custom-alexa-nodejs-lambda-helloworld-default",
            "awsRegion": "us-east-1",
            "codeUri": "lambda/custom",
            "functionName": "ask-custom-alexa-nodejs-lambda-helloworld-default",
            "handler": "index.handler",
            "revisionId": "cbb0fc82-d875-4697-a85d-9235871551d3",
            "runtime": "nodejs10.x"
          }
        ]
      }
    },
    "__ENVIRONMENT_ASK_PROFILE__": {
      "skill_id": "amzn1.ask.skill.ed038d5e-61eb-4383-a480-04e3398b398d",
      "was_cloned": false,
      "merge": {},
      "resources": {
        "manifest": {
          "eTag": "689365afa95f4182154f2b7af78f6072"
        },
        "interactionModel": {
          "es-ES": {
            "eTag": "56f78f703b60473a73bf6f35648e3647"
          }
        },
        "lambda": [
          {
            "alexaUsage": [
              "custom/default"
            ],
            "arn": "arn:aws:lambda:us-east-1:141568529918:function:ask-custom-alexa-nodejs-lambda-helloworld-default",
            "awsRegion": "us-east-1",
            "codeUri": "lambda/custom",
            "functionName": "ask-custom-alexa-nodejs-lambda-helloworld-default",
            "handler": "index.handler",
            "revisionId": "3db9aa7d-d76d-4adc-ab41-f9b546eb384a",
            "runtime": "nodejs10.x"
          }
        ]
      }
    }
  }
}
`

And in CLI v2 I get the error: [Error]: CliError: Skill package src is not found in ask-resources.json.

the .ask/config in v2 is:
`{
  "askcliStatesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillInfrastructure": {
        "@ask-cli/lambda-deployer": {
          "deployState": {
            "default": {
              "iamRole": "arn:aws:iam::141568529918:role/ask-lambda-testv2-1587847346433",
              "lambda": {
                "arn": "arn:aws:lambda:us-east-1:141568529918:function:ask-testv2-default-default-1587847348324",
                "lastModified": "2020-04-25T20:50:07.654+0000",
                "revisionId": "ef44443e-bca3-48de-bcee-17a0a1601411"
              }
            }
          }
        }
      },
      "skillId": "amzn1.ask.skill.713627f2-6490-49cd-9dd4-f574006f33cc",
      "skillMetadata": {
        "lastDeployHash": "iEs1uMb1/iBLqsI5tmrQWAx+dJw="
      },
      "code": {
        "default": {}
      }
    },
    "__ENVIRONMENT_ASK_PROFILE__": {
      "skillInfrastructure": {
        "@ask-cli/lambda-deployer": {
          "deployState": {
            "default": {
              "iamRole": "arn:aws:iam::141568529918:role/ask-lambda-testv2-1587847346433",
              "lambda": {
                "arn": "arn:aws:lambda:us-east-1:141568529918:function:ask-testv2-default-default-1587847348324",
                "lastModified": "2020-04-25T20:50:07.654+0000",
                "revisionId": "ef44443e-bca3-48de-bcee-17a0a1601411"
              }
            }
          }
        }
      },
      "skillId": "amzn1.ask.skill.713627f2-6490-49cd-9dd4-f574006f33cc",
      "skillMetadata": {
        "lastDeployHash": "iEs1uMb1/iBLqsI5tmrQWAx+dJw="
      },
      "code": {
        "default": {}
      }
    }
  }
}`

**Comment by xavidop** [comment]
UPDATE: In ASK CLI v1 if I am using the ASK_ACCESS_TOKEN, ASK_REFRESH_TOKEN and ASK_VENDOR_ID located in my ~/.ask/cli_config that was auto generated when I run ask init, it WORKS. but when I use the tokens generated by the command ask util generate-lwa-tokens the behaviour is the one explained above.

**Comment by brightsparc** [comment]
I am also seeing similar errror when using when [assuming role](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html) with an ACCESS_KEY_ID and SECRET_ACCESS_KEY and SESSION_TOKEN.

`[Error]: CliError: Skill package src is not found in ask-resources.json.`

I assume this is because the SESSION_TOKEN is not being picked up.

**Comment by xavidop** [comment]
Hello Amazon team!

Are there any update with this issue?

**Comment by kakhaUrigashvili** [comment]
@xavidop I opened a PR https://github.com/alexa/ask-cli/pull/167 to fix some issues blocking you from using env variables.

You will need to create "__ENVIRONMENT_ASK_PROFILE__" in ask-resources.json and possibly .ask/ask-states.json once the PR is merged.

**Comment by xavidop** [comment]
THANK YOU!!

**Comment by xavidop** [comment]
@kakhaUrigashvili did you check the behavior when you use refresh token and acces token generated by ask cli with ask util command?

**Comment by kakhaUrigashvili** [comment]
@xavidop Here are steps I did to check the behavior: 
1) generate token using `ask util generate-lwa-tokens`

2) moved/deleted $HOME/.ask/cli_config and $HOME/.aws/credentials files to simulate clean environment without any existing config files.

3) set following environment variables: 
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
ASK_REFRESH_TOKEN
ASK_VENDOR_ID

4) added section `__ENVIRONMENT_ASK_PROFILE__` in ask-resources.json and .ask/ask-states.json - I just copied from existing default profile.

5) ask deploy

It worked for me with the changes made in the PR https://github.com/alexa/ask-cli/pull/167

If you want test the PR you can:

1) pull the branch && npm install
2) npm link - this will make version from the branch available as a global command.

Feel free to help test the PR.

**Comment by xavidop** [comment]
okay, because with ask cli v1.7.23 and cli version v2.1.1 with the tokens generated from that command i recvieve this error:  


skill status checking...Error: Bad Request
Failed to refresh access token.

did you check it out with the last version of ask v1 cli?

**Comment by kakhaUrigashvili** [comment]
@xavidop I used version 2.5.0 to test.

**Comment by xavidop** [comment]
Could you test with latest version of v1?

**Comment by kakhaUrigashvili** [comment]
@xavidop I not able to fix anything in v1.

**Comment by xavidop** [comment]
Okay! I will upgrade my skills to v2 thank you!

**Comment by kakhaUrigashvili** [comment]
@xavidop I used PR branch https://github.com/alexa/ask-cli/pull/167 to test. Not v 2.5.0. The fix is not released yet.

**Comment by xavidop** [comment]
Understood, so I will wait for that PR

**Comment by kakhaUrigashvili** [comment]
@xavidop Your use case is CI/CD when you don't have cli_config and aws credentials files and want to pass everything with variables, right?

**Comment by xavidop** [comment]
Yes, it is

**Comment by kakhaUrigashvili** [comment]
@xavidop just released version 2.5.1. It should be fixed in this version.

**Comment by xavidop** [comment]
Thank you!
