### ISSUE TITLE
NLU evaluation methods have disappeared from ASK CLI v2

### ISSUE THREAD

**Issue by carlos-ocado** [alexa/ask-cli#145]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I just noticed that the commands for NLU evaluation do not appear anymore in the ask cli docs v2 (e.g. `create-nlu-annotation-set` doesn't apear):
https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#smapi-command

These commands were present in CLI v1: https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference-v1.html#create-nlu-annotation-set-subcommand

Also, a number of links in NLU evaluation docs section are now dead as a consequence: https://developer.amazon.com/en-US/docs/alexa/smapi/nlu-evaluation-tool-api.html#ask-cli

## Expected Behavior

- NLU commands to appear in ASK CLI v2 reference
- If not:
  - fix broken links in https://developer.amazon.com/en-US/docs/alexa/smapi/nlu-evaluation-tool-api.html#ask-cli
  - Mention deprecated methods in v1 to v1 Migration Guide. (https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html)

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
PR open https://github.com/alexa/ask-cli/pull/170

**Comment by kakhaUrigashvili** [comment]
Added in version 2.6.0 the following smapi commands
```
create-nlu-evaluations
list-nlu-evaluations
get-nlu-evaluation
get-result-for-nlu-evaluations
create-nlu-annotation-set
list-nlu-annotation-sets
update-properties-for-nlu-annotation-sets
get-properties-for-nlu-annotation-sets
delete-properties-for-nlu-annotation-sets
update-annotations-for-nlu-annotation-sets
get-annotations-for-nlu-annotation-sets
```

**Comment by btburton42** [comment]
@kakhaUrigashvili would it be possible to get this documentation updated as well?
https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html

or is there a better source?
