### ISSUE TITLE
`--debug` not providing necessary header info

### ISSUE THREAD

**Issue by timothyaaron** [alexa/ask-cli#147]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Adding `--debug` to `ask smapi import-skill-package` and `ask smapi create-export-request-for-skill` should provide the user with the id necessary for the subsequence, necessary `status` requests. 

According to [the docs](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#debug-mode-for-ask-cli-commands)...
> This debug message consists of these fields: timestamp, api-name, request-id, method, url, response-code, request-header, request-body, **response-header**, and response-body.

## Current Behavior
Without `--debug`, the command simply responds with "Command executed successfully!".

With `--debug`, that response is prepended with something like...
```
Operation: createExportRequestForSkillV1
Payload:
{
  "skillId": "amzn1.ask.skill.82kd9…",
  "stage": "live"
}
```

## Possible Solution
Any function that _requires_ a follow-up status request, should provide the information necessary to make that request without requiring a `--debug` flag. But the user should _at least_ be able to get the response headers using the flag.

## Your Environment and Context

* ask-cli version: 2.1.1
* Operating System and version: macOS Mojave 10.14.6
* Node.js version used for development: 13.7.0
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
@timothyaaron 
opened https://github.com/alexa/ask-cli/pull/149

**Comment by kakhaUrigashvili** [comment]
Added in version 2.2.0

**Comment by kakhaUrigashvili** [comment]
@timothyaaron we are planning to add --full-response flag next release. we also changing formatting when --debug flag is passed.
It is preferred to use --full-response for obtaining headers since we can potentially change output format when --debug flag is passed.

Here corresponding PR https://github.com/alexa/ask-cli/pull/200

Just wanted proactively reach out to you.
