### ISSUE TITLE
Quoted from other Github repo: ask clone command not working 

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#153]
Redirected from another Github repo, see original link at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/620.
> I'm trying to clone the skill from the developer console. when i run the below command. I'm getting the error.
ask clone "skills"
Command not recognized. Please run "ask" to check the user instructions.
If i try to deploy the skill to developer console i'm getting error as below:
C:\Users\reddymv\proactive-event-starter-api>ask deploy
[Warn]: Please make sure you are in the root directory of the project.
These issues happened after upgrading nodejs 10 to nodejs 12 and upgrading cli.
I'm thinking some installation files and settings have been misplaced.
Can anyone give info from starting to ending for the setup of ask-cli.

**Comment by RonWang** [comment]
Hi @sravankumarreddy9 ,

Please first check our [FAQ section](https://github.com/alexa/ask-cli/blob/develop/docs/FAQ.md#q-since-v2-ask-cli-removes-ask-clone-command-what-should-i-do-to-download-my-skill-project) about the removal of the clone command in CLI v2, and the replacement of the command. Please follow the suggestion to re-form your CLI v2 project. 

And your error message about the warning is because it's not a CLI-recognized project, it doesn't have the "ask-resources.json" for CLI to control the deploy logic. You will deploy successfully if you can follow the instruction above to create a v2 CLI supported skill project.

Thanks,
Ron

**Comment by sravankumarreddy9** [comment]
How can i degrade to CLI v1?

**Comment by RonWang** [comment]
@sravankumarreddy9 You can run `npm install -g ask-cli@1` to install the latest v1 CLI. May I ask if "clone" command is the reason you need to still use v1?

**Comment by sravankumarreddy9** [comment]
yes it was very convenient though. now after install cli v2 i'm not able to see .ask folder in my dir

**Comment by sravankumarreddy9** [comment]
C:\Users\reddymv>ask clone "skills"
Invalid json: C:\Users\reddymv\.ask\cli_config
check this please. There is no .ask folder after running command.

**Comment by RonWang** [comment]
Hey @sravankumarreddy9 ,

In v2 CLI we have changed our entire project structure for a longer term benefits. If you deploy your skill, you will figure the .ask folder still exists but used as the place to store built code and related states and IDs. The ask-resources.json file will be the configuration file for users to control their deploy.

And in terms of your question, could you check if the project is downloaded correctly? There should be a new project folder created after ask clone. And the correct json file path should be "{skillproj}\.ask\cli_config" if created correctly. Could you verify?

**Comment by sravankumarreddy9** [comment]
no my issue got resolved after deprecating the version. Everything working as before without errors.
Thank you for helping me in solving my problem. I have one last question i created a proactive event notification skill with standalone sender method. I want to create a skill with multiple proactive events in gamma or prod. I have gone lot of videos and articles nothing working out for me getting stucked at different points.

**Comment by RonWang** [comment]
By "gamma or prod" what do you mean? Do you stage your skill development? And I'm not sure about the "multiple events"... do you have the Lambda ARN for your "event" in skill.json, which can handle different events?

**Comment by sravankumarreddy9** [comment]
I'm not an advance guy in creating skills but trying to create a skill with multiple events. I created with one event and it runs successfully.

**Comment by RonWang** [comment]
Hey @sravankumarreddy9 , please see this [link](https://developer.amazon.com/en-US/docs/alexa/smapi/add-events-to-your-skill-with-smapi.html) to add the skill event endpoint in your skill.json file. Then in the Lambda's code, you can listen to the following [list of events](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-events-in-alexa-skills.html) and handle the event with your custom logic. If you have one event working, I'd assume it's pretty similar for multiple! Let me know if you any further questions~

Thanks,
Ron

**Comment by RonWang** [comment]
Close this issue and please feel free to reopen it if you have any question~
