### ISSUE TITLE
new permissions needed in AWS policy for cli v2

### ISSUE THREAD

**Issue by AnjaMarxAmazon** [alexa/ask-cli#161]
[Error]: The lambda deploy failed for Alexa region "default": AccessDeniedException: User: arn:XXX is not authorized to
 perform: lambda:UpdateFunctionConfiguration on resource: arn:XXX

need to update IAM policy for ask-cli v1 user explained here in the doc: https://developer.amazon.com/en-US/docs/alexa/smapi/manage-credentials-with-ask-cli.html#create-aws-credentials

to include 
lambda:UpdateFunctionConfiguration

which is currently not the case.

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon 
when AWS user is created using "ask configure" command it gets LambdaFullAccess permissions.

https://github.com/alexa/ask-cli/blob/develop/lib/utils/constants.js#L226
https://github.com/alexa/ask-cli/blob/develop/lib/commands/configure/aws-profile-setup-helper.js#L178

Was the user created using 'ask configure' command?

**Comment by AnjaMarxAmazon** [comment]
no, it was created using ask cli v1 and ask init
https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html does NOT state that you have to re-configure the AWS accounts nor ask users when migrating from v1 to v2.

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon ok we will take look into updating docs
https://developer.amazon.com/en-US/docs/alexa/smapi/manage-credentials-with-ask-cli.html#create-aws-credentials
and/or
https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon I will close this issue. I opened a request to update documentation for v1.
https://developer.amazon.com/en-US/docs/alexa/smapi/manage-credentials-with-ask-cli.html#create-aws-credentials

I think it makes sense to update v1 docs since based on v1 code it needs lambda:UpdateFunctionConfiguration permission as well.
