### ISSUE TITLE
add info about how to use cusotm ARN for new skill

### ISSUE THREAD

**Issue by AnjaMarxAmazon** [alexa/ask-cli#166]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-intro.html#create-new-skill
mentions the the lambda ARN can be configured for a new skill:
    "Deploy build artifacts to the configured AWS Lambda function. If this is the first time the skill has been deployed and a Lambda ARN has not been configured, the command creates a new Lambda function." I would expect more information in the ask-state.json file about HOW to configure an ARN.

## Current Behavior
there is not description of HOW the ARN can be configured

**CLI Snapshot**
ask new creates:
{
  "askcliStatesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillInfrastructure": {
        "@ask-cli/lambda-deployer": {
          "deployState": {}
        }
      }
    }
  }
}

## Steps to Reproduce (for bugs)
ask new

## Possible Solution
create the json structure so developers know where they can input an ARN
{
  "askcliStatesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillInfrastructure": {
        "@ask-cli/lambda-deployer": {
          "deployState": {
            "default": {
              "lambda": {
                "arn": "YOUR_ARN"
              }
            }
          }
        }
      }
    }
  }
}

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon we added support for sourceLambda in version 2.17.0 https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deploy-Command.md#ask-clilambda-deployer
