### ISSUE TITLE
Build zip file fails - Powershell script error

### ISSUE THREAD

**Issue by acerbisgianluca** [alexa/ask-cli#168]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
`ask deploy` should generate a zip file which contains lambda resources.

## Current Behavior
When I run `ask deploy` and it reaches _Build Skill Code_ step, I get `Impossibile elaborare la trasformazione degli argomenti nel parametro 'script:Verbose'. Impossibile convertire il
valore "System.String" nel tipo "System.Boolean". I parametri booleani accettano solo valori booleani e numeri, come $True, $False, 1 o 0.`. It says that the parameter `script:Verbose` got a _String_ instead of a _Boolean_.
At the end it also prints `Skill code built successfully.
Code for region default built to D:\Projects\Alexa Skill\voice-gram\skill\.ask\lambda\default\build.zip successfully with build flow python-pip.`, but that's not true.

During `Deploy Skill Infrastructure` (the next step) I get `[Error]: ENOENT: no such file or directory, stat 'D:\Projects\Alexa Skill\voice-gram\skill\.ask\lambda\default\build.zip'`

I think the problem is `${doDebug}` here https://github.com/alexa/ask-cli/blob/34f7c215fe727065dc284103d19c9bd73af16ee3/lib/controllers/skill-code-controller/code-builder.js#L65

## Steps to Reproduce (for bugs)
Run `ask deploy` on Windows 10 1909 using a Python based Lambda.

## Your Environment and Context

* ask-cli version: 2.5.1
* Operating System and version: Windows 10 1909
* Node.js version used for development: v13.10.1
* NPM version used for development: 6.13.7

**Comment by RonWang** [comment]
Hey @acerbisgianluca I wondered have you tried to unit test by running command `PowerShell.exe -Command "& {& '<the_path_to_the_python_build.ps1>' any_name.zip $true }"` directly at the location for your Lambda code in the cmd.exe? Could you try this and see if running the separate command should still fail at your machine? Sorry I cannot reproduce so I might need some more details why it's not changed to boolean, related to the powershell script or how CLI triggers this script.

And for the `the_path_to_the_python_build.ps1` you can just create a powershell script with the [source code](https://github.com/alexa/ask-cli/blob/develop/lib/builtins/build-flows/python-pip/build.ps1). Let me know if running this script directly work for you!

Ron

**Comment by acerbisgianluca** [comment]
Yup, it worked

**Comment by RonWang** [comment]
Hey @acerbisgianluca , then it's the same command that CLI executes in the code... there is only one different char, which is the usage of `$True` vs. `$true`, but should be the same string in Powershell. Though just in case, could you help to run the same command again but this time with 

`PowerShell.exe -Command "& {& '<the_path_to_the_python_build.ps1>' any_name.zip $True }"`

It's maybe on Windows 10 1909, $True is treated as System.string? If so, we can fix the CLI to use it. 

In the meantime, you could follow the steps below to first unblock yourself:
> 1. run (Get-Command cmd).Path to figure out where is the ask-cli installed -> some_path\nodejs\ask.cmd
> 2. Based on some_path, you find where you nodejs folder is. Open some_path\nodejs\node_modules\ask-cli\lib\controllers\skill-code-controllers\code-builders.js, [this line](https://github.com/alexa/ask-cli/blob/34f7c215fe727065dc284103d19c9bd73af16ee3/lib/controllers/skill-code-controller/code-builder.js#L64) to all lower case.

**Comment by acerbisgianluca** [comment]
Using `$True` worked too

**Comment by acerbisgianluca** [comment]
I found the error! My project's path included spaces so the script passed to the boolean argument a string. Removing spaces solved my issue.
