### ISSUE TITLE
Pushing team effort and managing profiles for multiple projects via ASK and CLI v2.5.0

### ISSUE THREAD

**Issue by almostSouji** [alexa/ask-cli#169]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current Behavior
If we are not just overseeing something there is not much if any information on the documentation for use cases like these, where multiple people develop code together and need to push it to different skills, an example on what fields ask-resources.json takes was not apparent either, despite it being mentioned multiple times in the [docs](https://developer.amazon.com/en-US/docs/alexa/smapi/quick-start-alexa-skills-kit-command-line-interface.html).

## Your Environment and Context

We are currently tasked to develop an Alexa skill in our university course, however are experiencing some hardship with managing a team effort based work flow.

The general idea is to have a uni internal gitlab as well as a team based amazon account to deploy the skill to while also allowing the same code base to be deployed to personal testing accounts (merging in modules from the uni gitlab as appropriate)

- We have tried to deal with this through the profile manager `ask configure` and each have a "personal" and "team" profile to facilitate this. 
- We created our personal test skill via `ask new`
- We pushed the team skill to the uni gitlab
- The others pulled the team skill from the uni gitlab

We then investigated how to tell the CLI which profile to use for which skill ID and stumbled over https://github.com/alexa/ask-cli/issues/164 and tried to apply this to our situation by modifying ask-resources.json

```json
{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "personal": {
      "skillInfrastructure": {
        "type": "@ask-cli/hosted-skill-deployer"
      },
      "skillId": "amzn1.ask.skill.---snip---"
    },
    "uni":{
      "skillInfrastructure": {
        "type": "@ask-cli/hosted-skill-deployer"
      },
      "skillId": "amzn1.ask.skill.---snip---"
    }
  }
}
```

However we are currently unsure on how to "set" a profile to use per branch, as seemingly the CLI still tries to resolve to default based on the following console output:

```
[Error]: Cannot resolve profile [default]
```` 

For ask cli v1 this was apparently done via `ask deploy -p uni` however using this just tells us to perform a git push instead

> [Warn]: Alexa hosted skills can be deployed by performing a git push.
> The master branch gets deployed to skill's development stage
> The prod branch gets deployed to skill's live stage
> Please run "git push" at the proper branch to deploy hosted skill to your targeted stage.

## Conclusion

We are currently out of guesses on what we are doing wrong with our intended workflow or what pieces of information we might be overlooking, any help would be greatly appreciated

After understanding what the issue in our case exactly is I'm more than happy to provide Feedback and suggestions on how to improve the documentation to make the required configuration clear.

* ask-cli version: 2.5.0
* Operating System and version: Windows10 1909 Build 18363-778
* Node.js version used for development: 13.7.0
* NPM version used for development: 6.9.0

**Comment by almostSouji** [comment]
### After digging some more i found the following to be probable

- The pre-push-hook gets the first (?) object key from the `.ask/ask-states.json`  `const profile = Object.keys(states.profiles)[0];` (`.git/hooks/pre-push` line:13)
- the credentials helper executes `!ask util git-credentials-helper --profile default` as specified in the `.git/config` file to retrieve the credentials for "default"
- the credentials helper then reads from `ask-resources.json` as specified in `lib/utils/constants.js`  to be executed in `index.js` of the credentials helper package

### This leads me to believe the following (under the current setup)

1. only one profile named "default" is supported through all of this
1. it has to be the first profile in `.ask/ask-states.json`
1. this profile also has to exist in `ask-resources.json`

After testing this with the above three points fulfilled the result was successful, however does not suggest that we have the capability to use different profiles for different skill remotes at all, due to the "hard" `--profile default` in the git config.

### Which also brings up the following question

why is this read from two different files? did we somehow manage to create a skill of a version with a different location for profiles than the ASK CLI credentials helper (ask-states vs ask-resources)? If so, how can we fix this?

### And the penultimate question:
Are multiple profiles for pushing to different alexa hosted skill repositories even supported, or are we stuck with just "default"?

**Comment by RonWang** [comment]
Hey @almostSouji sorry for the late response and thank you for the digging. Multi-developers skill development experience is really important to us, as it's one of the most significant benefits that local development brings. Using `profile` as the way to manage the skill development is also why we design this unit to manage credentials either Alexa or AWS. However, profile should not anymore be the solution when you use `@ask-cli/hosted-skill-deployer` (the Alexa-Hosted skill). 

This git-native skill development experience is prepared by ask-cli when you new/init an Alexa-Hosted skill. It's always one-codebase to one-skill, while CLI's profile concept can be one-codebase to multi-skill. That's why we always use the first profile in the ask-states (but I think it's not hard-coded 'default' but whatever comes the first). In Alexa-Hosted skill, you can manage the source version control as well as the skill stages using git's `master` branch or `prod` branch. Your team just need to focus on the git experiences, create your own feature branch and commit and push, and merge in `master` to test your changes. You cannot use profile here, because the git-credential that we use is a local setup and is profile-agnostic.

Thus, you don't need to work on the ask-resources file at all as there is not many things for you to configure, and ask-states is always the hidden file for cli to retrieve states, so you don't need to touch it. By the way, when you see `[Error]: Cannot resolve profile [default]` it's likely that you don't specify `--profile` when you run the command.

Let me know if this answers your question, or if you have any further question. I will try to come up with some action items based on your entire experiences once your question is answered.

**Comment by almostSouji** [comment]
@RonWang  The idea we had was to have personal alexa skills where we can independently "play around" and test things (with our own alexa dev console accounts) and one team account (with the team alexa dev console account) as acting "hand-in" (with the project leaders as testers, which actually gets published etc.) which share a code base we sync up through the univeristy gitlab (as that's another requirement to the hand-in flow)

If I understand you correctly you mean we should all work on the one alexa dev console account, set up our git users and push to this one skill only, but on different origin branches.

That'd remove the possibility to independently test around with utterances etc. in our own projects.

> Thus, you don't need to work on the ask-resources file at all as there is not many things for you to configure, and ask-states is always the hidden file for cli to retrieve states, so you don't need to touch it. By the way, when you see [Error]: Cannot resolve profile [default] it's likely that you don't specify --profile when you run the command.

said error appeared during debugging when i renamed the profile to be anything but "default" which i traced back to the pre-push hook and the git credentials manager config (`!ask util git-credentials-helper --profile default` line in `.git/config`) and goes against 

> That's why we always use the first profile in the ask-states (but I think it's not hard-coded 'default' but whatever comes the first)

Yes, the first entry is retrieved, however due to this mismatch with the git configs credentials helper input renaming the profile seems to backfire quite heavily

> Using profile as the way to manage the skill development is also why we design this unit to manage credentials either Alexa or AWS. However, profile should not anymore be the solution when you use @ask-cli/hosted-skill-deployer (the Alexa-Hosted skill)

Is there some notice on the documentation we just plain up missed mentioning this? Is `@hosted-skill-deployer` an optional dependency we missed and needed? we tried `ask init` with the skill id and profile switches which did configure the hosted skill properly

--- 

The ASK CLI v2 documentation shows profile switches for the `ask <command> --profile <profile>` commands, where we can pass something besides the default, to use "personal" or "uni", however since `ask deploy` has been switched to just tell us to push to git instead (unless we missed something extremely obvious there) this specific part of the workflow (pushing to the remote hosted alexa skill) does not take a profile switch (due to being native git commands) which used to be the case with `ask deploy`.

As our project lead uses v1.7 we tried reverting back and migrating our skill to that folder structure where we now experience none of the problems we had with v2 (this includes a change in the skills interaction model not applying to the skill when pushing the structure to origin/dev and origin/master, which might be worth its own issue if i can still reproduce it (requires some more time than currently available, as we're now back on v1 and i'd need to set up a test machine or container for that))

---

> Hey almostSouji sorry for the late response

Thank you for responding and looking into my gibberish at all, waiting for a response over the weekend was quite expected!

**Comment by kakhaUrigashvili** [comment]
@almostSouji  I think you can manage team project now in new version of ask cli.
With new version of ask-cli  git credentials helper and pre-push hook are only applied to Alexa hosted skill repo. You should be able to add more git remotes to manage project. I think you still should use 1 profile. You may need to reinitialize the project if it was created with older version of ask cli.

Here is a potential workflow:

Add additional remotes to git
`git remote add team-remote git@github.com:kakhaUrigashvili/test.git`

you can create new branch and associate with team remote

```
git checkout -b feature1
git add .; git commit -m'test'
git push --set-upstream team-remote feature1
```

when you are ready to deploy skill

```
git checkout master
git pull
git merge feature1
git push origin master
```
