### ISSUE TITLE
Equivalent of `ask api get-skill-credentials` in ASK CLI v2.x

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#172]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
In the pre-v2.x version of ASK CLI, `ask api get-skill-credentials` would obtain client ID and secret useful for sending messages to a skill. There does not appear to be an equivalent under `ask smapi`.

See https://developer.amazon.com/en-US/docs/alexa/smapi/skill-messaging-api-reference.html for mention of `ask api get-skill-credentials` and https://developer.amazon.com/en-US/docs/alexa/smapi/skill-credentials-api.html for the underlying SMAPI reference.

## Current Behavior
There does not appear to be an equivalent to `ask api get-skill-credentials` in ASK CLI v2.x.

## Steps to Reproduce (for bugs)
No reproduction steps, really. Just `ask smapi` and searched the list and couldn't find what I needed.

## Possible Solution
Implement equivalent command. Perhaps `ask smapi get-skill-credentials`.

## Your Environment and Context

* ask-cli version: 2.6.0
* Operating System and version: MacOS 10.15.2
* Node.js version used for development: v12.16.2
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
@habuma added 'ask smapi get-skill-credentials' in version 2.7.0.
