### ISSUE TITLE
[Feature Request] `ask add locale` command to add a new location for Skill

### ISSUE THREAD

**Issue by hideokamoto** [alexa/ask-cli#177]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

We want to be easier to add a new locale or language into exists skill.

```bash
$ ask add locale --language ja-JP
○ Update the `skill-package/skill.json`
○ Add a new model json in `skill-package/interactionModels/ja-JP.json`
```

The `skill-package/skill.json` is like this.
(Just copy exists locale's settings.)

```json
{
  "manifest": {
    "publishingInformation": {
      "locales": {
        "en-US": {
          "summary": "Sample Short Description",
          "examplePhrases": [
            "Alexa open hello world",
            "hello",
            "help"
          ],
          "name": "Cat Age Converter",
          "description": "Sample Full Description"
        },
        "ja-JP": {
          "summary": "Sample Short Description",
          "examplePhrases": [
            "Alexa open hello world",
            "hello",
            "help"
          ],
          "name": "Cat Age Converter",
          "description": "Sample Full Description"
        }
      },
      "isAvailableWorldwide": true,
      "testingInstructions": "Sample Testing Instructions.",
      "category": "KNOWLEDGE_AND_TRIVIA",
      "distributionCountries": []
    },
    "apis": {
      "custom": {}
    },
    "manifestVersion": "1.0"
  }
}
```

## Current Behavior

We have to add/create these JSON files manually.

## Motivation
Several CLI tools have a `add` or `generate` command to create any files.

https://ionicframework.com/docs/cli/commands/generate
https://angular.io/cli/generate
https://docs.nestjs.com/cli/usages#nest-add

I think this command will help us in developing the skill more easily.

**Comment by RonWang** [comment]
The new command `ask skill add-locales` is now added in v2.20.0.

Please check it out!
