### ISSUE TITLE
Utterance Profiler

### ISSUE THREAD

**Issue by xavidop** [alexa/ask-cli#179]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

With ASK CLI v2 --multi-turn-token option is mandatory

## Expected Behavior
As the official explanation of the Utterance profiler, it should be optional: https://developer.amazon.com/es-ES/docs/alexa/smapi/utterance-profiler-api.html

## Current Behavior
Now it is mandatory and I cannot test simple utterances without multi turn conversations

**CLI Snapshot**
Usage: ask smapi profile-nlu [options]

This is a synchronous API that profiles an utterance against interaction model.

Options:
  -u,--utterance <utterance>             [REQUIRED] Actual representation of user input to Alexa.
  --multi-turn-token <multi-turn-token>  [REQUIRED] Opaque string which contains multi-turn related context.
  -s,--skill-id <skill-id>               [REQUIRED] The skill ID.
  -g,--stage <stage>                     [REQUIRED] Stage for skill.
  -l,--locale <locale>                   [REQUIRED] The locale for the model requested e.g. en-GB, en-US, de-DE.
  -p, --profile <profile>                Provides the ASK CLI profile to use. When you don't include this option, ASK CLI uses the default profile.
  --debug                                Enables the ASK CLI  to show debug messages in the output of the command.
  -h, --help                             output usage information

## Steps to Reproduce (for bugs)
ask smapi profile-nlu -s ${skill_id} -l ${locale} --utterance "${utterance}" -g development

## Possible Solution
make --multi-turn optional and null by default

## Your Environment and Context

* ask-cli version: 2.6.0
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
This field is not marked as required in [ask-smapi-model](https://github.com/alexa/alexa-apis-for-nodejs/blob/master/ask-smapi-model/spec.json#L13641-L13652). This is an issue in the CLI's SMAPI command generation process from that package.

**Comment by xavidop** [comment]
Thank you!

**Comment by kakhaUrigashvili** [comment]
@xavidop fixed in 2.7.0

**Comment by xavidop** [comment]
it works guys thank you!
