### ISSUE TITLE
Find Utterance Conflicts in our Model

### ISSUE THREAD

**Issue by xavidop** [alexa/ask-cli#180]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Cannot find the equivalent ask cli command of ask api get-conflicts -s ${skill_id} -l ${locale} in V2

## Expected Behavior
It should check the utterance conflicts using the SMAPI: https://developer.amazon.com/en-US/docs/alexa/custom-skills/find-utterance-conflicts-in-your-model.html

## Current Behavior
Cannot find this option in v2

## Steps to Reproduce (for bugs)
ask smapi get-conflicts -s ${skill_id} -l ${locale}

## Your Environment and Context

* ask-cli version: 2.6.0
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by xavidop** [comment]
Hello team!

Do you know where the new version will be available?

Thank you for your support and your effort!

**Comment by kakhaUrigashvili** [comment]
@xavidop just released 2.7.0

**Comment by xavidop** [comment]
it works guys thank you!
