### ISSUE TITLE
~/.ask/cli_config is required even when using env vars

### ISSUE THREAD

**Issue by petermoon** [alexa/ask-cli#189]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

When all the necessary credentials are set up as env vars, `ask deploy` should deploy the skill and its backend as expected.

## Current Behavior

CLI displays this error:
`[Error]: CliFileNotFoundError: File /root/.ask/cli_config not exists.`

## Steps to Reproduce (for bugs)

Freshly install the CLI, set up credentials as env vars, run `ask deploy`

## Possible Solution

Don't always check for the existence of `cli_config`.
Make sure all deployment-related clients (ASK and AWS) know how to load credentials from env vars.

## Your Environment and Context

* ask-cli version: 2.2.0
* Operating System and version: ﻿Ubuntu 18.04.4 LTS running on Windows 10
* Node.js version used for development: v8.10.0
* NPM version used for development: 3.5.2

**Comment by kakhaUrigashvili** [comment]
@petermoon this already should be fixed since version 2.5.1 

https://github.com/alexa/ask-cli/issues/144
