### ISSUE TITLE
Configure command fails due to HTML response found while the system expects JSON

### ISSUE THREAD

**Issue by edopelawi** [alexa/ask-cli#193]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I have used ASK CLI a few times before, but somehow it fails when I try to do some operations today. I ended up removing my ASK CLI installation and reinstall it (via `npm install -g ask-cli`), and re-run `ask configure`.

## Expected Behavior

The `ask configure` commands should've opened a new URL in a browser to authenticate my account.

## Current Behavior

The `ask configure` command failed, due to `SyntaxError: Unexpected token < in JSON at position 0`.

**CLI Snapshot**

![Screen Shot 2020-05-15 at 12 33 17 AM](https://user-images.githubusercontent.com/5947111/82023808-ae54f500-9643-11ea-99d7-0ca5327db060.png)

## Steps to Reproduce (for bugs)

* Install the ASK CLI through NPM: `npm install -g ask-cli`
* Run the configure command: `ask configure`

## Your Environment and Context

* ask-cli version: 2.7.0
* Operating System and version: macOS Catalina, v 10.15.4
* Node.js version used for development: v10.10.0
* NPM version used for development: 6.10.3

**Comment by ck1125** [comment]
Triggering ask config with ASK_SKIP_NEW_VERSION_REMINDER environment variable like so:
`ASK_SKIP_NEW_VERSION_REMINDER=true ask configure` will avoid this happening as it doesn't do version check.

Ultimately, the fix would be to gracefully handle the JSON parse exception.

**Comment by kakhaUrigashvili** [comment]
@ck1125 and @edopelawi I opened PR for the fix https://github.com/alexa/ask-cli/pull/197

**Comment by edopelawi** [comment]
Thank you for the prompt response, folks! tried the suggestion above and it works now 🙌

**Comment by kakhaUrigashvili** [comment]
fixed in version 2.8.0
