### ISSUE TITLE
Skill enablement during ask deploy fails

### ISSUE THREAD

**Issue by ck1125** [alexa/ask-cli#194]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

ask deploy even though lambda deployment succeeds because the final step of skill enablement doesn't succeed. This is because when smapi util is kicked off the authorisation-controller has initialised AppConfig so it can use or refresh user  tokens if necessary.
## Expected Behavior

Skill deployment and enablement should succeed
## Current Behavior

Here's a output from a deploy run which shows that skill deployment succeeds but subequent smapi calls are failing to retrieve tokens that deployment will have used:
`✗ node_modules/.bin/ask deploy --profile profile-alexa

##########################################################################

[Info]: New MINOR version (v2.7.0) of ask-cli is available now. Current version v2.6.0.

It is recommended to use the latest version. Please update using "npm upgrade -g ask-cli".

##########################################################################

==================== Deploy Skill Metadata ====================

[Warn]: The hash of current skill package folder does not change compared to the last deploy hash result, CLI will skip the deploy of skill package.

Skill ID: skill_id

==================== Build Skill Code ====================

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm WARN rsk@1.0.0 No repository field.

npm WARN rsk@1.0.0 No license field.

added 71 packages from 124 contributors and audited 235 packages in 4.305s

1 package is looking for funding

  run `npm fund` for details

found 0 vulnerabilities

Skill code built successfully.

Code for region default+EU built to skill_code_workspace/.ask/lambda/rsk/build.zip successfully with build flow nodejs-npm.

==================== Deploy Skill Infrastructure ====================

  ✔ Deploy Alexa skill infrastructure for region "default"

  ✔ Deploy Alexa skill infrastructure for region "EU"

Skill infrastructures deployed successfully through @ask-cli/cfn-deployer.

==================== Enable Skill ====================

enabling skill skill_id

Failure happened at  TypeError: Cannot read property 'getToken' of null

    at AuthorizationController.tokenRefreshAndRead (skill_code_workspace/node_modules/ask-cli/lib/controllers/authorization-controller/index.js:69:73)

    at SmapiClient._smapiRequest (skill_code_workspace/node_modules/ask-cli/lib/clients/smapi-client/index.js:159:33)

    at Object.getSkillEnablement (skill_code_workspace/node_modules/ask-cli/lib/clients/smapi-client/resources/skill.js:122:13)

    at SkillMetadataController.enableSkill (skill_code_workspace/node_modules/ask-cli/lib/controllers/skill-metadata-controller/index.js:99:32)

    at Object.enableSkill (skill_code_workspace/node_modules/ask-cli/lib/commands/deploy/helper.js:84:25)

    at skill_code_workspace/node_modules/ask-cli/lib/commands/deploy/index.js:66:20

    at skill_code_workspace/node_modules/ask-cli/lib/commands/deploy/index.js:151:17

    at skill_code_workspace/node_modules/ask-cli/lib/commands/deploy/helper.js:66:9

    at skill_code_workspace/node_modules/ask-cli/lib/controllers/skill-infrastructure-controller/index.js:79:21

    at skill_code_workspace/node_modules/ask-cli/lib/controllers/skill-infrastructure-controller/index.js:157:24

[Error]: TypeError: Cannot read property 'getToken' of null
`

**CLI Snapshot**

## Steps to Reproduce (for bugs)

Run ask deploy with profile after ask configure.

## Your Environment and Context

* ask-cli version: 2.6.0
* Operating System and version: Mac OS & Ubuntu
* Node.js version used for development: v10.15.1
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@ck1125 thank you for reporting the issue. Are you able to provide more details steps to reproduce? I see what is the issue, but I was not able to reproduce.

**Comment by kakhaUrigashvili** [comment]
@ck1125 there was also issue in 2.6.0 with initiation of AppConfig. Can you try new version 2.7.0?

**Comment by ck1125** [comment]
2.7.0 seems to have fixed this issue so maybe it's no longer a problem.

**Comment by harshadak98** [comment]
[Error]: Target skill is not supported. Supported targets: skill-metadata,skill-infrastructure.
please help me with this error
