### ISSUE TITLE
build for build.zip fails if path contains spaces

### ISSUE THREAD

**Issue by AnjaMarxAmazon** [alexa/ask-cli#196]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

when running ask deploy, the build.zip is created in the .ask folder. in case the path to the skill project contains a space, the build.zip is not created in the correct directory and the lambda zip upload fails, even though the console reads that the zip was successfully created in the correct folder

## Expected Behavior
build.zip should be build in the .ask folder

## Current Behavior
Skill code built successfully.
Code for region default built to /Users/anjamarx/sample path/.ask/lambda/lambdacustom/build.zip **successfully with build** flow nodejs-npm.

==================== Deploy Skill Infrastructure ====================
  ✖ Deploy Alexa skill infrastructure for region "default"
[Error]: ENOENT: **no such file or directory,** stat '/Users/anjamarx/sample path/.ask/lambda/lambdacustom/build.zip'

**CLI Snapshot**

## Steps to Reproduce (for bugs)

create a directory containing a space character in the path, navigate to this folder and create a hello world skill there. run ask deploy

## Your Environment and Context

* ask-cli version: 2.6
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@AnjaMarxAmazon I have opened PR to fix it: https://github.com/alexa/ask-cli/pull/198

**Comment by kakhaUrigashvili** [comment]
fixed in version 2.8.0
