### ISSUE TITLE
How to best implement custom  DeployDelegate?

### ISSUE THREAD

**Issue by crixx** [alexa/ask-cli#204]
## I'm submitting a...

<pre><code>
[ X ] Request for implementation proposals for PR
</code></pre>

## Expected Behavior
It is possible and documented how to register custom DeployDelegates, e.g. to write a script that uses SAM to deploy to AWS or by using some other deployment tools.

## Current Behavior
There's a TODO in the relevant line: https://github.com/alexa/ask-cli/blob/426edfb52f2789ea22187633922870994d3aa178/lib/controllers/skill-infrastructure-controller/deploy-delegate.js#L157

## Possible Solution
Here is where I got stuck. Does someone have an idea what is a best-practice for such a thing? Any ideas on what a possible implementation could look like?

**Comment by kakhaUrigashvili** [comment]
@crixx we have deployed version 2.18.0 where we rewrote Cloud Formation deploy. It is much cleaner code with promises and async/await. You can use it as an example how to write a new deployer. If you decide to write your own deployer please open an issue/or PR with small prototype to make sure we are on the same page about it.

https://github.com/alexa/ask-cli/tree/develop/lib/builtins/deploy-delegates/cfn-deployer
