### ISSUE TITLE
please consider restoring `ask deploy --type [lambda|skill]` functionality

### ISSUE THREAD

**Issue by jessefarinacci** [alexa/ask-cli#205]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I manage the lambda function that provides the skill functionality outside of the ASK tool. I'd like to just be able to update the skill manifest. I don't have a lambda/ directory because I manage it outside of my ASK directory.

## Expected Behavior

Maybe restore the old functionality of `ask deploy --type/-t [lambda|skill]` so that I can just update the skill manifest on the semi-rare occasion it is required.

## Current Behavior

If I don't have any lambda/ code then `ask deploy` will fail. I can not update the skill-package/ directory which contains the manifest information.

**CLI Snapshot**
2.7.0

## Steps to Reproduce (for bugs)

`ask deploy --help`

## Possible Solution

`ask deploy --type skill`

## Your Environment and Context

* ask-cli version: 2.7.0
* Operating System and version: MacOS 19.4.0
* Node.js version used for development: 14.2.0
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
@jessefarinacci this can be accomplished by removing skillInfrastructure key from ask-resources.json
