### ISSUE TITLE
enum in -h options is missing entry 'default' for endpoint region

### ISSUE THREAD

**Issue by AnjaMarxAmazon** [alexa/ask-cli#213]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
           output usage information
$ ask smapi invoke-skill-end-point -h
Usage: ask smapi invoke-skill-end-point [options]

This is a synchronous API that invokes the Lambda or third party HTTPS endpoint for a given skill. A successful response will contain information related to what endpoint was called, payload sent to and received from the endpoint. In cases where requests to this API results in an error, the response will contain an error code and a description of the problem. In cases where invoking the skill endpoint specifically fails, the response will contain a status attribute indicating that a failure occurred and details about what was sent to the endpoint. The skill must belong to and be enabled by the user of this API. Also,  note that calls to the skill endpoint will timeout after 10 seconds. This  API is currently designed in a way that allows extension to an asynchronous  API if a significantly bigger timeout is required.

Options:
  -s,--skill-id <skill-id>                   [REQUIRED] The skill ID.
  -g,--stage <stage>                         [REQUIRED] Stage for skill.
  --endpoint-region <endpoint-region>        [REQUIRED] Region of endpoint to be called.
                                             [ENUM]: NA,EU,FE,**default**.
  --skill-request-body <skill-request-body>  [REQUIRED] ASK request body schema as defined in the public facing documentation
                                             (https://tiny.amazon.com/1h8keglep/deveamazpublsolualexalexdocs)
                                             [JSON]: JSON string or a file. Example: "$(cat {filePath})" or "file:{filePath}", either absolute or relative path are
                                             supported.
  -p, --profile <profile>                    Provides the ASK CLI profile to use. When you don't include this option, ASK CLI uses the default profile.
  --debug                                    Enables the ASK CLI  to show debug messages in the output of the command.
  -h, --help                                 output usage information

## Current Behavior
           output usage information
$ ask smapi invoke-skill-end-point -h
Usage: ask smapi invoke-skill-end-point [options]

This is a synchronous API that invokes the Lambda or third party HTTPS endpoint for a given skill. A successful response will contain information related to what endpoint was called, payload sent to and received from the endpoint. In cases where requests to this API results in an error, the response will contain an error code and a description of the problem. In cases where invoking the skill endpoint specifically fails, the response will contain a status attribute indicating that a failure occurred and details about what was sent to the endpoint. The skill must belong to and be enabled by the user of this API. Also,  note that calls to the skill endpoint will timeout after 10 seconds. This  API is currently designed in a way that allows extension to an asynchronous  API if a significantly bigger timeout is required.

Options:
  -s,--skill-id <skill-id>                   [REQUIRED] The skill ID.
  -g,--stage <stage>                         [REQUIRED] Stage for skill.
  --endpoint-region <endpoint-region>        [REQUIRED] Region of endpoint to be called.
                                             [ENUM]: NA,EU,FE.
  --skill-request-body <skill-request-body>  [REQUIRED] ASK request body schema as defined in the public facing documentation
                                             (https://tiny.amazon.com/1h8keglep/deveamazpublsolualexalexdocs)
                                             [JSON]: JSON string or a file. Example: "$(cat {filePath})" or "file:{filePath}", either absolute or relative path are
                                             supported.
  -p, --profile <profile>                    Provides the ASK CLI profile to use. When you don't include this option, ASK CLI uses the default profile.
  --debug                                    Enables the ASK CLI  to show debug messages in the output of the command.
  -h, --help                                 output usage information
**CLI Snapshot**

## Steps to Reproduce (for bugs)
run
$ ask smapi invoke-skill-end-point -h

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
issue will be fixed with next version of ask-smapi-model dependency
