### ISSUE TITLE
The CLI errors when deploying flash briefings.

### ISSUE THREAD

**Issue by alexandrenicol** [alexa/ask-cli#214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

When deploying a flash briefing skill using the ask-cli, and assuming that all the deployments have workd, the CLI should without exiting with an error code.

## Current Behavior

When deploying a flash briefing skill using the ask-cli (`ask deploy`), the CLI exits with an error code, even though the skill has been deployed. This seems to be due to the enable process failing. 

**CLI Snapshot**
<img width="1106" alt="Screenshot 2020-05-29 at 15 59 00" src="https://user-images.githubusercontent.com/6968775/83274306-875efd00-a1c5-11ea-8430-fabff83e4dfe.png">

## Steps to Reproduce (for bugs)

Create a Flash briefing skill using the ask-cli.
Deploy the skill with the command: `ask deploy`

A manifest example:

```
{
  "manifest": {
    "publishingInformation": {
      "locales": {
        "en-GB": {
          "summary": "Test",
          "examplePhrases": [],
          "name": "Flash briefing test",
          "description": "Tests.",
          "largeIconUri": "file://assets/icon_512.png",
          "smallIconUri": "file://assets/icon_108.png"
        }
      },
      "isAvailableWorldwide": true,
      "testingInstructions": "Enable, add to your flash briefings, and say 'Alexa, what's my news'. The message should contain the content.",
      "category": "WEATHER",
      "distributionCountries": []
    },
    "apis": {
      "flashBriefing": {
        "locales": {
          "en-GB": {
            "customErrorMessage": "Sorry, this flash briefing is not available at this time.",
            "feeds": [
              {
                "name": "Flash briefing test",
                "isDefault": true,
                "vuiPreamble": "Test :",
                "updateFrequency": "DAILY",
                "genre": "LIFESTYLE",
                "imageUri": "file://assets/icon_512.png",
                "contentType": "TEXT",
                "url": "TODO"
              }
            ]
          }
        }
      }
    },
    "manifestVersion": "1.0",
    "privacyAndCompliance": {
      "allowsPurchases": false,
      "usesPersonalInfo": false,
      "isChildDirected": false,
      "isExportCompliant": true,
      "containsAds": false
    }
  }
}

```

## Possible Solution

As a workaround more than a fix, would it be possible to have a flag to skip the enable process?

## Your Environment and Context

* ask-cli version: 2.9.0
* Operating System and version: MacOS 10.15.3 
* Node.js version used for development: 12.14.0
* NPM version used for development: 6.13.4

**Comment by kakhaUrigashvili** [comment]
@alexandrenicol thank you for reporting the issue.

looks like it the error explicitly throw in the ask cli

https://github.com/alexa/ask-cli/blob/develop/lib/controllers/skill-metadata-controller/index.js#L83

https://github.com/alexa/ask-cli/blob/develop/lib/utils/constants.js#L117

I will have research why we dont support flash briefing.

**Comment by RonWang** [comment]
Hey @alexandrenicol ,

Sorry for the wait. The enable-skill API that CLI calls does not allow the enablement for flashBriefing skills, with the similar reason as https://github.com/alexa/ask-cli/issues/212. So we cannot add the enablement of flashBriefing skill into the streamlined deploy process.

We can definitely fulfill your another request to not let if fail with the error status code. We will implement it. Does this solution sound good to you?

Thanks,
Ron

**Comment by alexandrenicol** [comment]
Hi @RonWang,

Thanks for the message, that's clear. Do you know if there's any future plan to add support for flash briefing enablement to the API? (FB skills don't use account linking, so I would assume it'd be easier than for smart home skill, as mentioned in #212.) 

In the meantime, it would be awesome if you could do the implementation to not let it fail with the error status code. We're using the CLI in an automated deployment flow, hence why it would be good if it didn't exit with an error code.

Thanks,
Alex

**Comment by RonWang** [comment]
Hey @alexandrenicol ,

I'm not super familiar with FB skill, but I think the `feed` hierarchy in skill.json plays similar effect as the accountLinking towards SmartHome/Video skill: they cannot be enabled (simulated) directly through API if without a valid runtime setup. 

And to your second point I totally agree, it should not be an error code. We will address that.

**Comment by RonWang** [comment]
@alexandrenicol please make sure you are using >v2.12.1 which contains the fix to this problem!

**Comment by alexandrenicol** [comment]
@RonWang Nice one, thanks!
