### ISSUE TITLE
Restore Deploy Options (--target)

### ISSUE THREAD

**Issue by AdonousTech** [alexa/ask-cli#218]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Please restore the ability to target only skill specific assets on deployment. For example ask deploy ---target skill. The updated behavior in V2 attempts to deploy the lambda function code on every deployment and frequently has issues with the "revisionId" in the ask-states.json file. For advanced users, there is no benefit to having the deployment of the AWS-hosted lambda function controlled by the ASK CLI deploy function. I can easily deploy my lambda code with the AWS CLI. I V1, I simply created a higher-level npm script to run `ask deploy --target skill` in addition to a concatenated script to deploy my lambda code (when necessary). The point is V1 allowed much more flexibility. V2 should have the same (if not more) flexibility. 

For example, I build skills using TypeScript. The build lambda build step of the V2 CLI does not know I have a TSC project. So, I still need to intervene and build the project in my original lambda/custom directory before handing off to ask deploy. It would have been easier to simply maintain the V1 flexibility.

I must say the upgrade experience from V1 to V2 was painful. Many of the changes make the development flow harder for experienced users as opposed to easier. I can see how V2 helps folks with little to no AWS experience. 

Why remove the --target option? 

## Expected Behavior

Simply bring back the --target options on the "deploy" command. They are *extremely* useful.

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@AdonousTech Since you manage lambda outside of the ask cli with aws cli, you can achieve desired outcome by removing "skillInfrastructure" property from ask-resources.json. 

I have created PR to add this info to the docs

https://github.com/alexa/ask-cli/pull/222

**Comment by AdonousTech** [comment]
Thanks!
