### ISSUE TITLE
Default `--skill-id` parameter for SMAPI commands

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#228]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Most/all SMAPI commands require the `--skill-id` or `-s` parameter. And, most of the time, I must glance at the `.ask/ask-states.json` file to copy the skill ID and paste it on the command line.

Since there is already precedent set for this kind of thing in #220, I'd like to be able to issue a `ask smapi` command without the `--skill-id` parameter and, if the `.ask/ask-states.json` file exists, have the skill ID used from that file.

## Current Behavior
Currently, `--skill-id`/`-s` is a required parameter on most/all SMAPI commands with the ASK CLI.

## Your Environment and Context

* ask-cli version: 2.10.1
* Operating System and version: MacOS 10.15.2
* Node.js version used for development: 12.16.2
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
Closing. Further discussion can be tracked in https://github.com/alexa/ask-cli/issues/227
