### ISSUE TITLE
ask dialog gives "[Error]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined" error

### ISSUE THREAD

**Issue by herrerodani** [alexa/ask-cli#238]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

when I execute "ask dialog --locale es-ES" in my project folder, an "[Error]: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined" arises.

## Current Behavior

**CLI Snapshot**
## Your Environment and Context

* ask-cli version: 2.10.2
* Ubuntu 18.04.4 LTS
* Node.js version v12.18.0
* NPM version used for development: 6.14.5

**Comment by herrerodani** [comment]
Tried in another Ubuntu with ask-cli 2.9.0 and worked. Upgraded to 2.10.2 and same error appeared.

**Comment by kakhaUrigashvili** [comment]
@herrerodani there is already PR open for this https://github.com/alexa/ask-cli/pull/236
Assuming you are using hosted skill.

**Comment by herrerodani** [comment]
closing as there is a related open issue.
