### ISSUE TITLE
If AWS region does not match, ask deploy hangs

### ISSUE THREAD

**Issue by bbezerra82** [alexa/ask-cli#241]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

If the AWS region configured in `$HOME/.aws/config` does not match the region where resources were deployed, there should be an error message.

## Current Behavior

Currently, there is no warning and `ask deploy` just hangs at 
```
==================== Deploy Skill Infrastructure ====================
  ⠇ Deploy Alexa skill infrastructure for region "default"
    → Validating the deploy state of existing Lambda function...
```

## Steps to Reproduce (for bugs)

- change the region at `$HOME/.aws/config`;
- go to a project folder that has been previously deployed;
- execute `ask deploy`;

## Possible Solution

- perform a check if the region on `$HOME/.aws/config` matches the one at `<project>/ask-resources.json` (potentially in other locations as well)

## Your Environment and Context

* ask-cli version: 2.10.2
* Operating System and version: Darwin/19.4.0
* Node.js version used for development: v10.19.0
* NPM version used for development: 6.14.5

**Comment by kakhaUrigashvili** [comment]
@bbezerra82 I tried to reproduce this with both lambda and cloud formation deploy, but I could not. Does this issue happens consistently?

**Comment by bbezerra82** [comment]
*sigh*

Looks like the "internet gnomes" fixed it already. I swear it was happening and changing the `$HOME/.aws/config` file fixed it for me. Now I keep moving it back and forth, executing `ask configure` and cannot reproduce it.

Closing the issue.
