### ISSUE TITLE
git push stuck at pre-push hasInProgressCerts

### ISSUE THREAD

**Issue by makandre** [alexa/ask-cli#253]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

`git push` should succeed

## Current Behavior

`git push` hangs

The follow command is executed repeatedly:

```
ask smapi get-certifications-list -p default -s <skillId>
```

**CLI Snapshot**

I looked inside the pre-push hook and suspect the problem to be the `do` loop here.  If I'm reading the code correctly, the `|| !inProgress` in the `while` condition keeps the loop running until the skill is in certification (but then push will be aborted precisely because the skill is in certification)

```
const hasInProgressCerts = () => {
  let nextToken;
  let inProgress = false;
  do {
    let resStr;
    try {
      const nextTokenOption = makeNextTokenOption(nextToken);
      resStr = getExecValue(`ask smapi get-certifications-list -p ${profile} -s ${skillId} ${nextTokenOption}`);
    } catch (err) {
      return false;
    }
    const resJson = JSON.parse(resStr);
    nextToken = resJson.nextToken;
    inProgress = resJson.items.some((val) => val.status === 'IN_PROGRESS');
  } while (nextToken || !inProgress);
  return inProgress;
};
```

## Steps to Reproduce (for bugs)

1. I use `ask init` to clone an existing Alexa-hosted skill
2. Commit some change
3. `git push` to `master`

## Your Environment and Context

* ask-cli version: 2.11.2
* Operating System and version: MacOS 10.15.4 (Catalina)
* Node.js version used for development: v10.15.3
* NPM version used for development: 6.9.0

**Comment by kakhaUrigashvili** [comment]
@makandre would you mind checking a few things to help troubleshooting:

1) try running: git push -v
2) check if ask-resources.json file is present
3) check if .ask/ask-states.json file is present

**Comment by makandre** [comment]
1. It just hangs:

   ```
   git push -v
   Pushing to https://git-codecommit.us-east-1.amazonaws.com/v1/repos/047c5e23-55a9-472b-bdba-67f340274491
   ```

2. present
3. present

As a workaround I commented out the `/* || !inProgress*/` part in the pre-push hook then the push succeeds.

**Comment by kakhaUrigashvili** [comment]
@makandre it is by design. The idea is to prevent push if the skill has a certification in progress. Of course, it is implemented in the pre-push hook, so it is easy to override as you did. Just want very that the push fails with error that certification in progress and not stuck forever?

**Comment by makandre** [comment]
I understand the intent of check, but I think the logic is wrong because it is preventing the push when my skill is **not** in certification.  As it is now, the loop will exit only when it finds an `IN_PROGRESS` status.

**Comment by kakhaUrigashvili** [comment]
@makandre I see. You are right. I think it needs to change to &&. I will update the script. For now, you can update it locally. The script is pulled from S3 bucket during initial clone of a hosted skill, so it would need to be updated manual for already cloned hosted skill.

**Comment by kakhaUrigashvili** [comment]
@makandre the script has been updated. thank you for reporting the issue.
