### ISSUE TITLE
[Feature Request] Unblock failed/in-progress builds

### ISSUE THREAD

**Issue by mhaddy** [alexa/ask-cli#255]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

A series of tasks get kicked off when `ask deploy` is called but if the deploy hangs or is accidentally cancelled by the developer, the developer is unable to run `ask deploy` again until some predetermined time in the future. Running `ask deploy` again while an import is in progress results in the following error message:

[Error]: {
  "message": "Found another import in progress for skillId: XXX. Use importId: YYY to track its status."
}

`ask smapi get-import-status` can be used to track the deploy status, but nothing can be done to manually fail/remove a stalled/hanging deploy.

## Expected Behavior
After tracking a deploy status, a developer should be able to manually fail and remove the stuck import job so they can run `ask deploy` again.

## Current Behavior
`ask smapi get-import-status` can be used to track the deploy status, but nothing can be done to manually fail/remove a stalled/hanging deploy.

## Possible Solution
See expected behaviour.

## Your Environment and Context

* ask-cli version: 2.10.x
* Operating System and version: Mac
* Node.js version used for development: 10, 12
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@mhaddy what is your proposed solution?

**Comment by mhaddy** [comment]
Create a SMAPI cancel import command that the ASK CLI can call. Appreciate this may be a future-dated request until such a SMAPI command exists.

**Comment by kakhaUrigashvili** [comment]
This is related to https://github.com/alexa/ask-cli/issues/291. The issue with handing deploy has been fixed by the service team.There is no plans by the service team to add API for reseting hanging deploy. I think the better solutions is for the service to handle error better and prevent hanging deploy in the first place.
