### ISSUE TITLE
[CLI] - The default folder name doesn't correspond with skill name

### ISSUE THREAD

**Issue by JoyceWYJ** [alexa/ask-cli#256]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x] Other... Please describe: Suggest to fix the default folder name to be same with skill name.
</code></pre>

When "ask new" a lambda skill or a CloudFormation skill (Alexa-hosted-skill is good): 

_? Please type in your skill name:  music player
? Please type in your folder name for the skill project (alphanumeric):  (Helloworld)_ 

 It's better to change the default name to "(musicplayer)" instead of "(Helloworld) ".

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: V2
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@JoyceWYJ it would be an easy change just need to remove `stringUtils.filterNonAlphanumeric(userInput.templateInfo.templateName) ||`
https://github.com/alexa/ask-cli/blob/develop/lib/commands/new/wizard-helper.js#L50

@RonWang it will be a little bit of a breaking change. Should we do it?

**Comment by kakhaUrigashvili** [comment]
@JoyceWYJ would you like to create PR for this request?

**Comment by kakhaUrigashvili** [comment]
merged. the change will be in the next release.
