### ISSUE TITLE
[CLI]- Should invocation name be changed to skill name automatically?

### ISSUE THREAD

**Issue by JoyceWYJ** [alexa/ask-cli#257]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x] Other... Please describe: Invocation name should be changed automatically.
</code></pre>

For Alexa-hosted-skill, the invocation name is changed in most scenarios, except when the skill name is default as ‘hello world skill’;
![image](https://user-images.githubusercontent.com/10021613/87613069-0f8b5a00-c6c1-11ea-840c-dc103005c385.png)

For Lambda skills and CloudFormation skills, the invocation name isn't changed.
It would be more convenient for users if the name is changed automatically.

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: v2
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@JoyceWYJ thank you for suggestion. I think this would a breaking change for people using replay file.

@RonWang what do you think?

**Comment by kakhaUrigashvili** [comment]
@JoyceWYJ would you like to create PR for this request?
