### ISSUE TITLE
SMAPI command: --param1(require value) --param2 value2, param2 will be used as the value for param1

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#259]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Assuming `ask smapi` has param1 and param2 which both require the value.
Running `ask smapi --param1 --param2 value2` expects the error message to tell: param1 is missing.

## Current Behavior

Running `ask smapi --param1 --param2 value2` will result in the message returned from service side to complain --param2 is not a valid value. And the target param2 is not set at all.

For example, If the param2 is --profile, then the profile parameter is not set to value2 when executing the command.

## Your Environment and Context

* ask-cli version: 2.11.1

**Comment by kakhaUrigashvili** [comment]
@RonWang Is this an example of this?
`ask smapi create-catalog-upload -c lala --catalog-upload-request-body --profile default`
If it is, I dont think there is a way to fix it. There is no way to know if "--profile" is value or flag. Of course, we can say if starts with '-' or '--' than it is a flag but it would be a little risky.

Only way this would work for enums. For example, we can validate that the value for stage is development or live.

**Comment by kakhaUrigashvili** [comment]
I have tested few cli applications and they all work the same way. For example, git:

```
git commit --fixup --squash
fatal: could not lookup commit --squash
```
