### ISSUE TITLE
ask configure -l or --list-profiles does not work

### ISSUE THREAD

**Issue by talkingnews** [alexa/ask-cli#263]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
According to https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#configure-command profiles should be listed

## Current Behavior
    "unknown option"

## Steps to Reproduce (for bugs)

```
$ ask configure -l
error: unknown option '-l'
$ ask configure --list-profiles
error: unknown option '--list-profiles'
```

## Your Environment and Context

* ask-cli version: 2.12.0
* Operating System and version: 5.4.0-1018-aws #18-Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Node.js version used for development: v12.18.2
* NPM version used for development: 6.14.6

**Comment by kakhaUrigashvili** [comment]
@talkingnews the docs are incorrect. --list-profiles has been removed in v2. You can retrieve list of profiles from $HOME/.ask/cli_config.

**Comment by talkingnews** [comment]
Thanks - is this the right place to report it then? The "contact us" link on that page leads to https://developer.amazon.com/alexa/console/contact-us which doesn't have a "documentation" category, but I could use "other"?

**Comment by kakhaUrigashvili** [comment]
@talkingnews I will find out what is the best channel to report documentation discrepancies. I have created a request internally to fix this specific issue.

**Comment by kakhaUrigashvili** [comment]
the docs have been updated.
