### ISSUE TITLE
[Feature request] Support AWS CodeCommit for ask new template

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#269]
Original feature request : https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/550

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
```
 ask new --template-url https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/XXXX-Alexa-Template
```

**Comment by RonWang** [comment]
@StefanV85 do you think option `--template-branch` is also needed in the ask-new command? We will possibly support it anyway, but your input would also be pretty valuable to us. Let us know your use case and thanks in advance.

**Comment by kakhaUrigashvili** [comment]
@RonWang opened a PR https://github.com/alexa/ask-cli/pull/273

**Comment by RonWang** [comment]
@StefanV85 Please check the latest version of ask-cli@v2.14.0. Close this issue.
