### ISSUE TITLE
Upgrade from ASK CLI v1 to v2 resulted in [Error]: [object Object]

### ISSUE THREAD

**Issue by epsilon-rmroch** [alexa/ask-cli#274]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I used the upgrade utility to upgrade my Alexa Skill from ASK CLI v1 to v2.  Now when I use "ask deploy" I get [Error]: [object Object].

## Expected Behavior
The code should deploy

## Current Behavior
PS C:\amazon\Sea_of_Thieves> ask deploy --debug
==================== Deploy Skill Metadata ====================
[Warn]: The hash of current skill package folder does not change compared to the last deploy hash result, CLI will skip the deploy of skill package.
Skill ID: amzn1.ask.skill.526885bc-2e73-4d78-bbab-c7e0ff4901be

==================== Build Skill Code ====================
###########################
###########################
Installing skill dependencies based on package.json.
npm WARN us-east-1_seaofthieves@1.0.0 No description
npm WARN us-east-1_seaofthieves@1.0.0 No repository field.

npm install dependencies successfully.
Zipping source files and dependencies to C:\amazon\Sea_of_Thieves\.ask\lambda\lambdaus-east-1SeaOfThieves\build.zip.
###########################
Codebase built successfully
###########################
Skill code built successfully.
Code for region default built to C:\amazon\Sea_of_Thieves\.ask\lambda\lambdaus-east-1SeaOfThieves\build.zip successfully with build flow nodejs-npm.

==================== Deploy Skill Infrastructure ====================
  × Deploy Alexa skill infrastructure for region "default"
[Error]: [object Object]

-------------------- Debug Mode --------------------
[2020-07-29T13:53:51.272Z] - DEBUG - GET_NPM_REGISTRY
GET http://registry.npmjs.org/ask-cli/latest
status code: 200 OK

Request headers: {"User-Agent":"ask-cli/2.13.0 Node/v12.16.1 Windows_NT/10.0.18362"}

Response headers: {"date":"Wed, 29 Jul 2020 13:53:49 GMT","content-type":"application/json","transfer-encoding":"chunked","connection":"close","set-cookie":["__cfduid=deeef3e93f94ea95465df03f1ff7e2acf1596030829; expires=Fri, 28-Aug-20 13:53:49 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax"],"cf-ray":"5ba7540e9cb60368-ORD","vary":"Accept-Encoding","cf-cache-status":"DYNAMIC","cf-request-id":"043c72dd2000000368cc02b200000001","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","server":"cloudflare"}

Response body: "{\"name\":\"ask-cli\",\"version\":\"2.13.0\",\"description\":\"Alexa Skills Kit (ASK) Command Line Interfaces\",\"bin\":{\"ask\":\"bin/ask.js\"},\"engines\":{\"node\":\">=8.3.0\"},\"license\":\"Apache 2.0\",\"repository\":{\"type\":\"git\",\"url\":\"git+https://github.com/alexa/ask-cli.git\"},\"author\":{\"name\":\"RonWang\",\"email\":\"nongwang@amazon.com\"},\"keywords\":[\"alexa\",\"skill\",\"cli\",\"package\",\"cloudformation\",\"serverless\",\"deploy\"],\"scripts\":{\"test\":\"node ./node_modules/mocha/bin/_mocha -t 10000 -u exports -R spec test/unit/run-test.js\",\"test:watch\":\"node ./node_modules/mocha/bin/_mocha test/unit/run-test.js -w\",\"test:report\":\"nyc --cache npm test && nyc report --reporter=html\",\"test:browser\":\"npm run test:report && open coverage/index.html\",\"integration-test\":\"mocha -t 180000 test/integration/run-test.js\",\"functional-test\":\"mocha -t 180000 test/functional/run-test.js\",\"lint\":\"eslint lib/builtins lib/clients lib/commands lib/controllers lib/model lib/view\",\"pre-release\":\"standard-version\",\"prism\":\"prism\"},\"dependencies\":{\"adm-zip\":\"^0.4.13\",\"archiver\":\"^1.1.0\",\"ask-smapi-model\":\"1.10.0\",\"ask-smapi-sdk\":\"^1.2.0\",\"async\":\"^2.1.5\",\"aws-profile-handler\":\"2.0.3\",\"aws-sdk\":\"^2.288.0\",\"axios\":\"^0.19.2\",\"bunyan\":\"^1.8.12\",\"chalk\":\"2.4.2\",\"commander\":\"^4.1.1\",\"date-fns\":\"^2.7.0\",\"folder-hash\":\"^3.0.0\",\"fs-extra\":\"^2.1.0\",\"inquirer\":\"^6.2.0\",\"js-yaml\":\"^3.13.1\",\"jsonfile\":\"^2.4.0\",\"listr\":\"^0.14.3\",\"module-alias\":\"^2.1.0\",\"mustache\":\"^4.0.1\",\"open\":\"^7.0.3\",\"ora\":\"^3.4.0\",\"portscanner\":\"^2.1.1\",\"pretty-bytes\":\"^5.1.0\",\"ramda\":\"^0.27.0\",\"request\":\"^2.79.0\",\"rxjs\":\"^6.5.2\",\"semver\":\"^5.3.0\",\"shelljs\":\"^0.8.2\",\"simple-git\":\"^1.82.0\",\"tmp\":\"^0.1.0\",\"uuid\":\"^3.4.0\",\"valid-url\":\"^1.0.9\"},\"devDependencies\":{\"@commitlint/cli\":\"^8.2.0\",\"@commitlint/config-conventional\":\"^8.2.0\",\"@stoplight/prism-cli\":\"^3.3.3\",\"chai\":\"^3.5.0\",\"chai-json-schema\":\"^1.5.1\",\"chai-uuid\":\"^1.0.6\",\"coveralls\":\"^3.0.2\",\"eslint\":\"^6.8.0\",\"eslint-config-airbnb-base\":\"^14.0.0\",\"eslint-plugin-import\":\"^2.20.1\",\"gulp\":\"^3.9.1\",\"husky\":\"^4.2.3\",\"mocha\":\"^3.2.0\",\"mocha.parallel\":\"^0.15.6\",\"nyc\":\"^13.3.0\",\"proxyquire\":\"^1.7.11\",\"sinon\":\"^6.0.0\",\"standard-version\":\"^8.0.1\"},\"husky\":{\"hooks\":{\"pre-commit\":\"npm run lint\",\"commit-msg\":\"commitlint -E HUSKY_GIT_PARAMS\",\"pre-push\":\"npm run test:report\"}},\"nyc\":{\"check-coverage\":true,\"lines\":95,\"statements\":95,\"functions\":95,\"branches\":95,\"include\":[\"lib/utils/string-utils.js\",\"lib/utils/url-utils.js\",\"lib/utils/zip-utils.js\",\"lib/utils/hash-utils.js\",\"lib/utils/retry-utility.js\",\"lib/builtins/*\",\"lib/clients/*\",\"lib/model/*\",\"lib/view/*\",\"lib/controllers/*\",\"lib/commands/*\"],\"exclude\":[\"lib/clients/aws-client/aws-util.js\"]},\"_moduleAliases\":{\"@root\":\".\",\"@src\":\"./lib\",\"@test\":\"./test\"},\"gitHead\":\"999dfbd8687d88c5dbf821659e8f0e1784c07f6f\",\"bugs\":{\"url\":\"https://github.com/alexa/ask-cli/issues\"},\"homepage\":\"https://github.com/alexa/ask-cli#readme\",\"_id\":\"ask-cli@2.13.0\",\"_npmVersion\":\"6.4.1\",\"_nodeVersion\":\"11.4.0\",\"_npmUser\":{\"name\":\"ask-dev-tools\",\"email\":\"ask-tools@amazon.com\"},\"dist\":{\"integrity\":\"sha512-bSp8bwJxZSu2HwmGf6rS+pBrVeZFeS00+McaSax3cp8FKcTSvi4I8hxzun+5w6tPKb2UfpgswAO5ApknaUD8AQ==\",\"shasum\":\"38696e45b5aba08e335039efe1bb00e385568a3d\",\"tarball\":\"https://registry.npmjs.org/ask-cli/-/ask-cli-2.13.0.tgz\",\"fileCount\":303,\"unpackedSize\":2040800,\"npm-signature\":\"-----BEGIN PGP SIGNATURE-----\\r\\nVersion: OpenPGP.js v3.0.4\\r\\nComment: https://openpgpjs.org\\r\\n\\r\\nwsFcBAEBCAAQBQJfF19KCRA9TVsSAnZWagAAxRAP/A8ku0XsDT3XYH7UynqV\\nQ59GSgWrADl09AOzy2eDjxu9+uOng3pDGTxAKkTwYnerFKmF9uJsKnjx3POt\\nA/xopsWaPRE82RjfrrRQT6Mi+3Uoa/Q1Wk3U31MxcnbtXF6c2IXs+KdEj0y0\\ny9lq8BciDu1ZtVsU3Z67+LXWBem3GTyc9A4NSQuVVhaxmCCW35poExTLGYOH\\nc3F0n6jrvoRQQbU+kICDQnQcdUUyW2SMLE8zcpk6L5K4eEP61EP2rk5CZ7gF\\n9N5HXAp5AACmIdfKdEIi2JrwDUPrtsa0SZEapjIkjvjZ6EOUO+4JAiNGUuT0\\nLnhB8BYEJfFnny/49spPXBSMlzHAJNmzwVflLOL8kVNFAZiLhWL7K/Y6CCV8\\nEICbF6MvLXqXXw4NMc1j3cJT3JL+5RCZXrhGvSSizOHaRWoZfM9rW6d8PIHR\\n63/U/EiwwFcz1i+OAmHOcV4PDivHXduAH7I0go4oopLKkIzCuZ6pmtUWzKWT\\ncpAI0pBZrR2LPrV8z27Wa3KGyRhV85BjESW6dBIjX8vV9mIlndJ9AcQL2Dv8\\nltDtR78dKrc/ebJbgSoorMy2wA1ixHujnEndH56gNK4BS+HIi2YwjYdaXu6E\\nQb6TJNKNK/EVZkLohceGyuIdkkpeXPLpsatdWbpeyTujbLnEB3B4eKf4IULm\\n1vgH\\r\\n=bB68\\r\\n-----END PGP SIGNATURE-----\\r\\n\"},\"maintainers\":[{\"name\":\"ask-dev-tools\",\"email\":\"ask-cli@amazon.com\"}],\"directories\":{},\"_npmOperationalInternal\":{\"host\":\"s3://npm-registry-packages\",\"tmp\":\"tmp/ask-cli_2.13.0_1595367241468_0.20074567302607105\"},\"_hasShrinkwrap\":false}"

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: 2.13.0
* Operating System and version: Windows 10 Pro
* Node.js version used for development: 12.16.1
* NPM version used for development: 6.13.4

**Comment by kakhaUrigashvili** [comment]
@epsilon-rmroch would you mind commenting with the cause and resolution? May be we can improve the error message.

**Comment by kakhaUrigashvili** [comment]
@epsilon-rmroch opened PR to fix error message https://github.com/alexa/ask-cli/pull/275
