### ISSUE TITLE
Add ask smapi and SMAPI REST support for adding Custom Tasks

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/ask-cli#276]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Custom Tasks are used for Skill Connections and Quick Links that require parameters. The only way to associate Custom Task definition files and the tasks section in skill.json is by issuing `ask deploy`.

The `ask deploy` command is a course-grained CLI approach that does many things. SMAPI REST and `ask smapi` are more fine-grained. There are lots of other tools and frameworks that are based on SMAPI and don't work with `ask deploy`. It is OK for `ask deploy` to be more tightly coupled to ASK SDK and require a specific project folder structure. But SMAPI should allow for flexibility where the `tasks` folder is located.

When a feature is added to `ask deploy`, there should always be a SMAPI way of doing it.

The speed and breadth of adoption of Custom Tasks will be greatly improved by adding a specificy SMAPI way of doing this.

## Expected Behavior

Add an ASK CLI command such as `ask smapi update-skill-custom-tasks` and a corresponding SMAPI REST endpoint that supports uploading task definition files from a development project to the Alexa Skill Developer Console.

Alternatively, consider adding the feature to an exising SMAPI command such as `update-skill-manifest`.

## Current Behavior

Currently, the only way to deploy custom tasks is to use `ask deploy`. Custom tools or frameworks (other than ASK SDK) often have different project structures or workflows. The `ask deploy` solution won't work from them. The lack of a SMAPI-specific command for custom tasks is slowing down its adoption and limiting their use by designers and developers that are using other tools and frameworks.

**CLI Snapshot**

## Possible Solution

- Add a SMAPI REST endpoint for uploading task definition files
- Update the ASK CLI to include a `ask smapi update-skill-custom-tasks` command
- Alternatively add this support to `update-skill-manifest` or other existing ASK CLI SMAPI command
- At least show in the Alexa Developer Console a read-only list of task definition files that were successfuly uploaded

## Your Environment and Context

* ask-cli version: 2.13.0
* Operating System and version: Windows 10
* Node.js version used for development: v12.13.0
* NPM version used for development: 6.13.4

**Comment by rmtuckerphx** [comment]
Our team is using Jovo Framework v3 and jovo-cli v3.0.21. We are ready to implement Quick Links now and have spent 2 days trying to get things that already worked with Jovo CLI to work with `ask deploy`. This is for multiple projects across multiple stages (local, dev, qa, staging, prod) all with working CI/CD pipelines. This time could have been spent implementing and experimenting with Quick Links and Custom Tasks. 

With a SMAPI solution to uploading custom task definition files, it gives the flexibility that tools such as Jovo needs to quickly support their developer base. It is a win for Amazon and win for the tool creator and a win for the developer.

**Comment by daviddlow** [comment]
+1; many top skills live on Jovo in particular and are amongst the earliest adopters of new features like this.  It would be great to give this request some support.

**Comment by kakhaUrigashvili** [comment]
@rmtuckerphx and @daviddlow thank you for the feature request. Currently, the SMAPI API does not expose an endpoint to update custom tasks. I will create a requests for the SMAPI team to add this functionality.
There are currently 2 options for updating custom tasks:
1) 'ask deploy --target skill-metadata' (as you already mentioned above).
2) creating an upload url, uploading zip with the skill package and importing the skill package as described in https://developer.amazon.com/en-US/docs/alexa/smapi/skill-package-api-reference.html. Essentially, doing the same steps as ask deploy command doing.

**Comment by rmtuckerphx** [comment]
@kakhaUrigashvili 
Why would the following command: `ask deploy --target skill-metadata`
Result in this error?

```
==================== Deploy Skill Metadata ====================
[Error]: {
  "skill": {
    "resources": [
      {
        "action": "UPDATE",
        "name": "InteractionModel.en-US",
        "status": "FAILED"
      },
      {
        "action": "UPDATE",
        "name": "Manifest",
        "status": "ROLLBACK_SUCCEEDED"
      },
      {
        "action": "CREATE",
        "name": "TaskDefinitions",
        "status": "FAILED"
      }
    ],
    "skillId": "amzn1.ask.skill.1b..."
  },
  "status": "FAILED"
}
```

Does the FAILED interaction model affect the overall status when I only targeted the skill metadata?

**Comment by RonWang** [comment]
Hey @rmtuckerphx , so here is the difference between v1 and v2 CLI: I know in v1 when you specify --target=skill only skill.json will be updated, here the skillMetadata component in v2 denotes all the JSON files for a skill-id, including skill.json, InteractionModels, ISPs or Tasks. That is the [skill package](https://developer.amazon.com/docs/alexa/smapi/skill-package-api-reference.html) that CLI will deploy as a bundle.

In case of your response from the skillPackage service,  this meant your InteractionModel and TaskDefinitions are not correct, deploy failed; while skill manifest is updated without problem, but rolledback with the failure of any other resource. The overall status is FAILED for this operation.

**Comment by RonWang** [comment]
Hey @rmtuckerphx we have forwarded this feature request to our service team, and they are gradually making progress to release this feature. I will close this issue as nothing can be done from our end, please stay tuned in the future CLI release - we will announce in the changelog as well.
