### ISSUE TITLE
More documentation issues - new profile information does not make sense

### ISSUE THREAD

**Issue by talkingnews** [alexa/ask-cli#279]
##UPDATE - resolution found

There are some serious documentation issues. I finally figured it out and have opened the following tickets:
https://github.com/alexa/alexa-cookbook/issues/263
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/638

## Original post

Hi again, continuing this https://github.com/alexa/ask-cli/issues/264 as I still cannot make this work and I cannot re-open that issue.

At the page
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-smapi-sdk
it says
"Create a new security profile for your Amazon Developer account by following the instructions provided here"
where "here" is "https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#generate-lwa-tokens"
But that tells me how to generate an LWA token, not how to create a new login profile.

Then it says at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-smapi-sdk
"Using the ASK CLI, run: ask util generate-lwa-tokens. You will be asked to provide the Client ID and Client Secret keys from the previous step. This will return the following JSON with a Refresh Token"

But it doesn't - it makes me login via a link (need to use the --no-browser option) and again, I don't get to choose the profile.

So then when I try and plugin the client secret like this:

ask util generate-lwa-tokens --client-id amzn1.application-oa2-client.2axxx --client-confirmation dd3xxx --no-browser

I think "client_confirmation" is a confusing way to refer to "client_secret"

We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Error Summary
400 Bad Request
An unknown scope was requested
Request Details
response_type=code
client_id=amzn1.application-oa2-client.2axxxxx
state=15xxxxx
scope=alexa%3A%3Aask%3Askills%3Areadwrite%20alexa%3A%3Aask%3Amodels%3Areadwrite%20alexa%3A%3Aask%3Askills%3Atest%20alexa%3A%3Aask%3Acatalogs%3Aread%20alexa%3A%3Aask%3Acatalogs%3Areadwrite%20alexa%3A%3Aask%3Asubscriptions%20alexa%3A%3Aask%3Askills%3Adebug
redirect_uri=https%3A%2F%2Fask-cli-static-content.s3-us-west-2.amazonaws.com%2Fhtml%2Fask-cli-no-browser.html

(this decodes to alexa::ask:skills:readwrite alexa::ask:models:readwrite alexa::ask:skills:test alexa::ask:catalogs:read alexa::ask:catalogs:readwrite alexa::ask:subscriptions alexa::ask:skills:debug)

*UPDATE:*I finally found this page: https://developer.amazon.com/settings/console/securityprofile/overview.html

This is not mentioned anywhere, but has LOADS of security tokens where I have been trying over and over. But although they are in the form of as skill ID like amzn1.ask.skill.32xxxxx  none of them match my skill IDs. Are these safe to delete?

If I just do ask util generate-lwa-tokens --no-browser then it generates a link like: 

 https://www.amazon.com/ap/oa?response_type=code&client_id=amzn1.application-oa2-client.aad3xxxxx < this doesn't seem to relate to any of the profiles at https://developer.amazon.com/settings/console/securityprofile/overview.html so while I get access and refresh tokens, I don't know what I am putting in const clientId for this example https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-smapi-sdk#for-nodejs

And I can't seem to match that to anything at ~/home/.ask/cli_config

**Comment by kakhaUrigashvili** [comment]
@talkingnews Looks like one of the lwa scopes added recently is not supported for all developer accounts.

https://github.com/alexa/ask-cli/commit/f8e2d0f30b477ea6d0fc02532e568627a2071f9c

If I remove this scope I am able to use "ask util generate-lwa-tokens" command. I will discuss with the team the fix. 

As a quick workaround you can use ask cli version prior 2.13.0.

**Comment by talkingnews** [comment]
Thank you @kakhaUrigashvili -  however, I am still unable to find the correct scope for use with smapi node client.

For example, this works:
`ask smapi get-interaction-model --skill-id amzn1.ask.skill.80fXXXXX --stage development --locale en-GB`

But this does not, even if I use the exact same credentials as the ask CLI, or I get new ones.

`smapiClient.callGetInteractionModelV1('amzn1.ask.skill.80fXXXXX', 'development', 'en-GB')`

I just get

`response: { message: 'User has not consented to this operation.' }`

I can do everthing else with the node smapi client, but not interactionmodel functions

`ask util generate-lwa-tokens --client-id amzn1.application-oa2-client.02dXXXX --client-confirmation 382XXXXX --no-browser --scopes alexa::ask:skills:readwrite alexa::ask:models:readwrite alexa::ask:skills:test alexa::ask:catalogs:read alexa::ask:catalogs:readwrite alexa::ask:subscriptions alexa::ask:skills:debug`

I have tried different scopes, including with and without the skills:debug

I have also added more details to another user's post with a similar problem
https://forums.developer.amazon.com/questions/89552/login-with-amazon-says-user-has-not-consented-but.html

**Comment by RonWang** [comment]
Hey @talkingnews please check the response in https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/638 and if you still have question we can continue the conversation here~

**Comment by kakhaUrigashvili** [comment]
@talkingnews scopes need to be double quoted.

ask util generate-lwa-tokens --client-id amzn1.application-oa2-client.xxx --client-confirmation 1a0eecxxxxa --scopes "alexa::ask:skills:readwrite alexa::ask:models:readwrite alexa::ask:skills:test alexa::ask:catalogs:read alexa::ask:catalogs:readwrite"

Sorry about that. I will put a request to add example to the docs.

**Comment by kakhaUrigashvili** [comment]
@talkingnews I have create a request to add example to the docs. I am going to close this issue since there are no action items for the ask cli.

**Comment by shanedroid** [comment]
thank you @talkingnews for piecing together your experience around this and linking so cleanly to the other related issues, you really saved me some time today as I also got bamboozled by trying to read the docs and figure out how to get started using `ask-cli` to fetch a needed [refresh token](https://developer.amazon.com/docs/login-with-amazon/refresh-token.html)

To reiterate - for anyone else who is looking to use the `ask-cli` to fetch tokens for use in authenticating an alexa skill this is the doc you should follow:

https://developer.amazon.com/en-US/docs/alexa/smapi/get-access-token-smapi.html
