### ISSUE TITLE
ask deploy fails 

### ISSUE THREAD

**Issue by abhinavjayanthy** [alexa/ask-cli#283]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Deploy fails saying lambda function name is more than 64 characters. 
## Expected Behavior

Give an option to change the lambda function name

## Current Behavior

The ask profile I deal with is a little long, so when deploying the skill for the first time, the process of creating the lambda function fails as the name is more than 64 chars.

Also, when I create a new lambda function and add it to the skill and update the arn in skill.json and then run "ask deploy" the CLI doesn't take the newly created lambda function but tried to make a new lambda function. Unfortunately it fails ( because of the above problems)

**CLI Snapshot**

## Steps to Reproduce (for bugs)

Create a skill on the dev console, create a new lambda function, attach it to the skill and then clone the skill.Try deploying it and see that CLI create a new lambda function instead of using the newly created one. 
## Possible Solution

Option to name the lambda function when creating a skill which is not Alexa hosted, or reducing the name of the auto generated lambda function name so that it fits the AWS criteria. 

## Your Environment and Context

* ask-cli version: 2.14.0
* Operating System and version: Mac os, 10.14.6
* Node.js version used for development: 10.15
* NPM version used for development:6.14.6

**Comment by kakhaUrigashvili** [comment]
@abhinavjayanthy I think may be your profile name is too long. We can shrink it like we do for skill name or you can use shorter profile name.

https://github.com/alexa/ask-cli/blob/develop/lib/clients/aws-client/lambda-client.js#L152

**Comment by abhinavjayanthy** [comment]
@kakhaUrigashvili yes, the profile name is long, but I created a new lambda function and updated the skill.json, when i try to deploy it with this, it still tries to create a new function, any particular reason why ?

**Comment by kakhaUrigashvili** [comment]
@abhinavjayanthy 
if there is no skillInfrastructure state information in .ask/ask-states.json and there is skillInfrastructure property in ask-resources.json, the cli assumes it is a new skill and it will try create a lambda.

If you don't want to use the cli to manage the lambda, just remove  skillInfrastructure property from .ask/ask-states.json and ask-resources.json. 

Then if you run "ask deploy" only skill package will be deployed.

If you still want to have a custom lambda name(which is not currently supported), you may have to modify lambda information in .ask/ask-states.json file.

**Comment by abhinavjayanthy** [comment]
This is the ask-resources.json after removing the the skillInfrastructure 
`{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "UniversalStudiosInteractive": {
      "skillMetadata": {
        "src": "./skill-package"
      },
      "code": {
        "default": {
          "src": "./lambda"
        }
      }
    }
  }
}`

This is ask-states.json after removing the skillInfrastructure property
`{
  "askcliStatesVersion": "2020-03-31",
  "profiles": {
    "UniversalStudiosInteractive": {
      "skillId": "amzn1.ask.skill.bff2f349-665b-444a-b0d9-e46ea926a4dc",
      "skillMetadata": {
        "lastDeployHash": "+GaJqfUWtkJC+XQLBIjaQsai5k8="
      }
    }
  }
}`

the deploy fails with the following error 

ESTOTSWL1PPHVML:TrollsTopia Abhinav$ ask deploy --profile "UniversalStudiosInteractive"
[Warn]: Failed to find the ask-resources.json file to deploy with from the current directory.
ESTOTSWL1PPHVML:TrollsTopia Abhinav$ ls
ask-resources.json      infrastructure          lambda                  skill-package
ESTOTSWL1PPHVML:TrollsTopia Abhinav$ 

PS. The infrastructure folder is empty

**Comment by abhinavjayanthy** [comment]
This is the ask-resources.json after removing the the skillInfrastructure
{ "askcliResourcesVersion": "2020-03-31", "profiles": { "<profile name>": { "skillMetadata": { "src": "./skill-package" }, "code": { "default": { "src": "./lambda" } } } } }

This is ask-states.json after removing the skillInfrastructure property
{ "askcliStatesVersion": "2020-03-31", "profiles": { "<profile name>": { "skillId": "amzn1.ask.skill.bff2f349-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "skillMetadata": { "lastDeployHash": "+GaJqfUWtkJC+XQLBIjaQsai5k8=" } } } }

the deploy fails with the following error

![Screen Shot 2020-08-17 at 10 28 50 AM](https://user-images.githubusercontent.com/33322133/90408117-66e06980-e075-11ea-9935-37dbd673ec27.png)



PS. The infrastructure folder is empty

**Comment by abhinavjayanthy** [comment]
This is the ask-resources.json after removing the the skillInfrastructure
`{ "askcliResourcesVersion": "2020-03-31", "profiles": { "<profile name>": { "skillMetadata": { "src": "./skill-package" }, "code": { "default": { "src": "./lambda" } } } } }`

This is ask-states.json after removing the skillInfrastructure property
`{ "askcliStatesVersion": "2020-03-31", "profiles": { "<profile name>": { "skillId": "amzn1.ask.skill.bff2f349-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "skillMetadata": { "lastDeployHash": "+GaJqfUWtkJC+XQLBIjaQsai5k8=" } } } }`

the deploy fails with the following error

![Screen Shot 2020-08-17 at 10 28 50 AM](https://user-images.githubusercontent.com/33322133/90408485-de15fd80-e075-11ea-9a7e-7f59dd7f2928.png)


PS. The infrastructure folder is empty

**Comment by kakhaUrigashvili** [comment]
@abhinavjayanthy can you try using branch from this PR https://github.com/alexa/ask-cli/pull/282 ? I am sure this error message is not correct.


`
npm uninstall -g ask-cli
git clone https://github.com/alexa/ask-cli.git
cd ask-cli
git fetch --all
git checkout fix-error-messagex
npm install
npm link
`

**Comment by abhinavjayanthy** [comment]
@kakhaUrigashvili checkoing out the branch `fix-error-messagex` seems to have the skill meta deploy and building the code ( which can be removed as per the #284 ) but we still have the issue about how to deploy the lambda code.

**Comment by kakhaUrigashvili** [comment]
@abhinavjayanthy Do you want to use ask cli to deploy lambda code or you want to handle it yourself? It you want ask cli to handle you need to rename to a shorter profile name (you can change in $HOME/.ask/cli_config) and just use lambda name that is auto created by the cli.

If you dont want to ask cli manage the lambda, you can remove skillInsfrastruture property and use something like aws cli to deploy lambda.

**Comment by abhinavjayanthy** [comment]
@kakhaUrigashvili I would like to use the CLI as I have testing and deploy scripts connected in a Travis build. I ended up changing the profile name and the deploy was successful. 

Thank you so much for your help. 

Also, it would be good to have the ability to name our own lambda function or attach an existing lambda function.

**Comment by abhinavjayanthy** [comment]
@kakhaUrigashvili I would like to use the CLI as I have testing and deploy scripts connected in a Travis build. I ended up changing the profile name and the deploy was successful. 

Thank you so much for your help. 

Also, it would be good to have the ability to name our own lambda function or attach an existing lambda function.

**Comment by kakhaUrigashvili** [comment]
@abhinavjayanthy we added support for sourceLambda in version 2.17.0 https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deploy-Command.md#ask-clilambda-deployer
