### ISSUE TITLE
Cloning skill with ASK CLI - resulting in error

### ISSUE THREAD

**Issue by HeIp** [alexa/ask-cli#286]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Trying to Code with offline tools on local machine running 
<code>ask init --hosted-skill-id amzn1.ask.skill.X-X-X-X-X</code>
Expecting it to clone/copy/download the code on aws to my machine.

## Current Behavior

Instead of downloading the code for offline use CLI returns the following:

**CLI Snapshot**
![image](https://user-images.githubusercontent.com/31706214/90668379-02acd980-e21e-11ea-82e4-39e070ba19f8.png)

## Steps to Reproduce (for bugs)

1)run <code>ask init --hosted-skill-id amzn1.ask.skill.X-X-X-X-X</code>
2)see error as shown in snapshot above

## Possible Solution

Work Around:
1)Get VS code and get Alexa Skills KiT (ASK) ToolKit plugin
2) Set up the plugin with aws account/credentials
3) Click Import existing skill
4) Click skill name planning to import
5) Pick folder location
6) Code downloads successfully

## Your Environment and Context

* ask-cli version: 2.14.0
* Operating System and version: Windows_NT x64 10.0.19041
* Node.js version used for development: 14.5.0
* NPM version used for development: 6.14.7

**Comment by kakhaUrigashvili** [comment]
@HeIp ask init for hosted skill should work if run it inside of an empty folder. It seems like you are running the command inside of a folder that already have initialized git repo.

**Comment by HeIp** [comment]
@kakhaUrigashvili I actually created an empty folder and ran the command in the newly created empty folder and still resulted in the same way.

**Comment by kakhaUrigashvili** [comment]
@HeIp I was able to reproduce the issue. 

.ask and .ask-resources.json should be in .gitignore on the master branch. If you dont have them it would cause this issue.
When ask init runs it first creates .ask and .ask-resources.json.

https://github.com/alexa/ask-cli/blob/develop/lib/controllers/hosted-skill-controller/index.js#L64

then clones git repo and tries to checkout master branch. If there are conflicts the git checkout fails.

I will have to discuss with the team about the solution.

**Comment by HeIp** [comment]
Thank you for looking into this !
I'll add them to the git ignore now.
Just weird that the work around solution I mentioned works without a problem.
Thanks again @kakhaUrigashvili

**Comment by cbothra** [comment]
Hi, I tried all the above solution but nothing works for me. It just throws me below error message:

`[Error]: {
  "message": "Resource not found."
}`

Just to mention I am not using git. Still I added .ask and .ask-resources.json file in .gitignore. Besides that I created this skill with ASK CLI V2 and deployed it and everything worked fine. When I try to clone it in another folder then it throws me the above error.

Any help?

**Comment by HeIp** [comment]
Have you tried using the vscode extension ?

**Comment by kakhaUrigashvili** [comment]
> Hi, I tried all the above solution but nothing works for me. It just throws me below error message:
> 
> `[Error]: { "message": "Resource not found." }`
> 
> Just to mention I am not using git. Still I added .ask and .ask-resources.json file in .gitignore. Besides that I created this skill with ASK CLI V2 and deployed it and everything worked fine. When I try to clone it in another folder then it throws me the above error.
> 
> Any help?

@cbothra would you mind providing detailed steps to help reproduce the issue?

**Comment by cbothra** [comment]
@HeIp Yes I tried the vscode extension but wasn't very comfortable with it. So switched back to terminal :)

@kakhaUrigashvili Here are the detailed steps.
**1.** Installed latest version of ASK CLI using `npm install -g ask-cli`
**2.** Configured my aws account using `ask configure`
**3.** Created skill using `ask new` (helloworld template)
**4.** Deployed skill using 'ask deploy'
**5.** Tested the skill in the dashboard.

Everything works like a charm till here.

**6.** Now created an empty folder.
**7.** Tried to clone the skill using `ask init --hosted-skill-id amzn1.ask.skill.X-X-X-X-X`

At **step 7.** it throws me error `[Error]: { "message": "Resource not found." }`
 
Hope this helps.

**Comment by cbothra** [comment]
I think I got the answer from the migration guide.
```
To migrate skill code hosted on AWS Lambda to a local machine, export the skill code from AWS Lambda. After the skill code has been downloaded, run ask init within the project directory to download Alexa Skill Package resources and set up the project for deployment using the ASK CLI.

To migrate an Alexa-hosted skill code to a local machine, run ask init --hosted-skill-id HOSTED_SKILL_ID with the skill identifier of the Alexa-hosted skill.
```

Thanks @everyone for the quick reverts. I really appreciate that.

**Comment by HimanshuPrimo** [comment]
I am getting this error while cloning the code from the Alexa Developer console on Ubuntu. 

Skill clone failed. Reason: Command failed: git branch --show-current

![image](https://github.com/alexa/ask-cli/assets/121434728/03099b24-0c38-4e6c-b326-440f0a25b542)
