### ISSUE TITLE
[Feature request] Upgrade cfn-deployer to support the s3 upload if stack creates AWS S3 resource(s)

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#289]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

This feature request is created on behalf of @JoeMoCode.

Two of our Alexa official templates https://github.com/alexa/skill-sample-nodejs-web-api-my-cactus and https://github.com/alexa/skill-sample-nodejs-facts-aws-microservice build public web services for the skill, where they wish to use cfn-deployer to deploy the skill and web API together using `ask deploy`. 

The current issue is s3 won't be uploaded if only using naive AWS CloudFormation APIs. Users still have to upload the content separately after the s3 created by `ask deploy`. 

## Expected Behavior

When user run `ask deploy` with a stack which contains s3 resources ([like this](https://github.com/alexa/skill-sample-nodejs-facts-aws-microservice/blob/master/Final/Fact-Service/template.yml#L81)), user is not expected to upload s3 assets manually after the deployer. 

Considering many services require existing s3 artifacts in Cloudformation, supporting s3 upload from local to service would make other AWS services available as well.

## Current Behavior

User's s3 bucket created in cfn-deployer can only be used as a "placeholder", it needs content uploaded before using.

## Possible Solution

Introduce hooks for deployer, or looking at existing Cloudformation solution which links local file in the stack might help solve the issue. SAM or serverless are all possible solutions.

**Comment by RonWang** [comment]
This will also be helpful for the repo https://github.com/alexa/skill-sample-nodejs-web-api-my-cactus

**Comment by kakhaUrigashvili** [comment]
@JoeMoCode and @RonWang we added outputs to .ask/ask-states.json in version 2.18.0. I think you can achieve what you are looking for now.

https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Alexa-Skill-Project-Definition.md#askask-statesjson-this-file-is-managed-by-cli-only-should-be-read-only
