### ISSUE TITLE
Instructions on obtaining ClientID are impossible to follow

### ISSUE THREAD

**Issue by error454** [alexa/ask-cli#312]
## I'm submitting a...
<pre><code>
[X] Documentation issue or request
</code></pre>

The documentation on [creating a list skill using the ask cli](https://developer.amazon.com/en-US/docs/alexa/smapi/steps-to-create-a-list-skill.html) is impossible to complete.

## Expected Behavior
General documentation bug. I expect instructions to be correct and up to date and to lead me to the same result as explained in the documentation. The problem is this specific instruction:

> Go to https://developer.amazon.com/home.html. Select Settings > Security Profiles. In this list, search for the same SkillId that you copied. Click on this SkillId, and select Web Settings. Copy the ClientId value.

## Current Behavior
After following all instructions up to this point, when opening the Security Profiles page, the page is completely empty (there are no security profiles). There is the option to create a new security profile, but when created there is no obvious way to link said security profile to a skill.

## Steps to Reproduce (for bugs)
* Follow the instructions on the above-linked page
* Look for security profiles and note that none exist

## Your Environment and Context
* ask-cli version: 2.15.0
* Operating System and version: Ubuntu subsystem for Linux on Win 10
* Node.js version used for development: 10.19.0
* NPM version used for development: 6.14.4

**Comment by kakhaUrigashvili** [comment]
@error454 Thank you for reporting the issue.

Our team does not maintain those documentation pages. There are few options how we can improve the page:

1) Click feedback button and provide the feedback to maintainer's of the doc page.
2) You can help us by contributing to the ask cli docs in our repo: https://github.com/alexa/ask-cli/tree/develop/docs
3) We can create an internal ticket to pass your feedback.

Option 1 is probably the most efficient.

**Comment by error454** [comment]
> 1. Click feedback button and provide the feedback to maintainer's of the doc page.
Where does this button live? I searched the doc page and came up empty.

I'm ultimately searching for an answer to the problem, If I had the answer I would contribute it. Is there a place where amazon employees answer technical issues like this?

**Comment by kakhaUrigashvili** [comment]
@error454 I have a grey button in the right/bottom corner. 

You can also try https://forums.developer.amazon.com

**Comment by error454** [comment]
> @error454 I have a grey button in the right/bottom corner.

So you are here: https://developer.amazon.com/en-US/docs/alexa/smapi/steps-to-create-a-list-skill.html
And you have a grey button that says "Feedback" in the bottom right corner?

I see no such button. I searched all HTML elements and source code in the inspector and the word feedback does not exist on my version of that page. I am logged in with my dev account.

> You can also try https://forums.developer.amazon.com

I did [post a question there about 2 weeks ago](https://forums.developer.amazon.com/questions/231717/cannot-obtain-clientid-no-security-profiles.html). It does seem to be a place to ask questions, but does not seem to be a place where you get answers from amazon employees.

**Comment by kakhaUrigashvili** [comment]
@error454
Here is a screenshot

https://paste.pics/A9PVT

looks like feedback button is an image and it loads asynchronously after the page load.  
https://syd1.qualtrics.com/WRQualtricsSiteIntercept/Graphic.php?IM=IM_dakGFivcS6ABTcF

may something blocking it since it is from different domain.

**Comment by kakhaUrigashvili** [comment]
@error454 I have also opened an internal ticket for the documentation team.

**Comment by error454** [comment]
Thank you @kakhaUrigashvili, I confirmed that brave was blocking the feedback button. I just submitted feedback for that page.

**Comment by kakhaUrigashvili** [comment]
@error454 I am going to close the issue. I don't think there are any remaining actions in this issue.
