### ISSUE TITLE
ASK CLI - no more clone option; how to download existing skill entirely?

### ISSUE THREAD

**Issue by paul-uz** [alexa/ask-cli#342]
It looks like the ASK CLI had a clone feature, back in 2017, and it no longer exists.

We have a skill on our account that needs updating, but we have lost the code for it, so I need to download everything; the code and the skill config files.

I tried `ask smapi export-package` but it only downloaded the skill package (skill.json) and not the `ask-states.json` which is seeminlgy required to switched the skill to a new custom ARN.

How can I export/download the **full** skill?

**Comment by kakhaUrigashvili** [comment]
@paul-uz If it was Alexa hosted skill you need to run 'ask init --hosted-skill-id <hosted-skill-id>'.

**Comment by paul-uz** [comment]
@kakhaUrigashvili it's not a hosted skill.

I just want to download an alexa skill in its entirety.

**Comment by kakhaUrigashvili** [comment]
@paul-uz if it is not alexa hosted skill then the code/lambda would be in your AWS account. ask cli v1 all it was doing is downloading lambda code using aws sdk for lambda code and  downloading skill package for configurations.

you can possibly do the same by
1) ask smapi export-package
2) aws lambda get-function

**Comment by RonWang** [comment]
Yes @paul-uz please check https://github.com/alexa/ask-cli/blob/develop/docs/FAQ.md#q-since-v2-ask-cli-removes-ask-clone-command-what-should-i-do-to-download-my-skill-project for the detailed reason and the replacement flow. Thanks!
