### ISSUE TITLE
ask new with the Lambda option selected doesn't create a  .git directory/git repo

### ISSUE THREAD

**Issue by allenabc** [alexa/ask-cli#346]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior

After "ask new" with the lambda option should create a .git directory/git repo

## Current Behavior

a local git repo should be created pointing to lambda directory  "master"

**CLI Snapshot**

## Steps to Reproduce (for bugs)

ask new with AWS Lambda

ask new
Please follow the wizard to start your Alexa skill project ->?
Choose the programming language you will use to code your skill: NodeJS?
Choose a method to host your skill's backend resources: AWS Lambda Host your skill code on AWS Lambda (requires AWS account).?
Choose a template to start with: Hello world Alexa's hello world skill to send the greetings to the world!?
Please type in your skill name: myskill?
Please type in your folder name for the skill project (alphanumeric): myskill
Project for skill "myskill" is successfully created at /home/allen/myskill
allen@allenComputer:~/myskill$

ask deployDeploy configuration loaded from ask-resources.jsonDeploy project for profile [default]
==================== Deploy Skill Metadata ====================
Skill package deployed successfully.Skill ID: amzn1.ask.skill.08d6ccba-5f3f-40c0-a5fd-0c45fcb19636
==================== Build Skill Code ====================
Skill code built successfully.Code for region default built to /home/allen/myskill/.ask/lambda/build.zip successfully with build flow NodeJsNpmBuildFlow.
==================== Deploy Skill Infrastructure ====================
Deploy Alexa skill infrastructure for region "default"     
The api endpoints of skill.json have been updated from the skill infrastructure deploy results.Skill infrastructures deployed successfully through @ask-cli/lambda-deployer.
==================== Enable Skill ====================
Skill is enabled successfully.allen@allenComputer:~/myskill

$ git status 
fatal: not a git repository (or any of the parent directories): .gitallen@allenComputer:~/myskill$

## Your Environment and Context

* ask-cli version: ask 2.20.0
* Operating System and version: Ubuntu 18.04 LTS
* Node.js version used for development:node v10.19.0
* NPM version used for development:npm 6.14.9

**Comment by kakhaUrigashvili** [comment]
@allenabc why do you think 'ask new' should initialize git repo? What if a developer does not use git (uses subversion for example)? Do you think it is outside of the 'ask cli' scope?

**Comment by RonWang** [comment]
And because we serve as the deploy tool for Alexa skills, the source version control for the project is still up to the user to choose.
I think the VSCode extension could be a good place for this feature - a checkbox "initialize with .git" - when a project starts. XCode does this way.

**Comment by allenabc** [comment]
As it stands now the workflow is broken. 

ask new
followed by
ask deploy doesn't work because a .git directory is missing


Discussion:

There are several SCM's but falling back to that reason isn't helpful to the end user.
The Hello World skill is 308k. Reasonably a more complex skill could be a few megs. 
Anyway, asking the user to setup git, when **ask new** should do a default git connection 
to a AWS file system isn't helpful to a developer who just wants to write a skill. 

In the rare case, when the user doesn't want to use the free service from Amazon, he/she is 
welcome to go to all that extra work to setup his own SCM connection.

As you know, In the "GUI" https://developer.amazon.com/alexa/console/ask a new skill automatically is setup to
a Amazon git server. 




allen@allenComputer:/tmp$ ask new
Please follow the wizard to start your Alexa skill project ->
? Choose the programming language you will use to code your skill:  NodeJS
? Choose a method to host your skill's backend resources:  Alexa-hosted skills
  Host your skill code by Alexa (free).
? Choose the default locale for your skill:  en-US
? Choose the default region for your skill:  us-east-1
? Please type in your skill name:  hwone
? Please type in your folder name for the skill project (alphanumeric):  hwone

Project directory for hwone created at
        /tmp/hwone

Lambda code for hwone created at
	./lambda

Skill schema and interactionModels for hwone created at
	./skill-package

Skill is enabled successfully.
Hosted skill provisioning finished. Skill-Id: amzn1.ask.skill.e14b58ad-5364-4088-9359-7e66ff88404c
Please follow the instructions at https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#askcli to learn more about the usage of "git" for Hosted skill.

allen@allenComputer:/tmp$ cd hwone/
allen@allenComputer:/tmp/hwone$ ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

[Warn]: Alexa hosted skills can be deployed by performing a git push.
The master branch gets deployed to skill's development stage
The prod branch gets deployed to skill's live stage
Please run "git push" at the proper branch to deploy hosted skill to your targeted stage.
allen@allenComputer:/tmp/hwone$

**Comment by kakhaUrigashvili** [comment]
@allenabc based on the example above you are setting up Alexa Hosted Skill. 'ask deploy' does not work with Alexa hosted skill. To deploy Alexa hosted skill use git commands: git add .; git commit -m'message'; git push

https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Alexa-Hosted-Skill-Commands.md

```
a483e7e143b4:test kakuri$ ask new
Please follow the wizard to start your Alexa skill project ->
? Choose the programming language you will use to code your skill:  NodeJS
? Choose a method to host your skill's backend resources:  Alexa-hosted skills
  Host your skill code by Alexa (free).
? Choose the default locale for your skill:  en-GB
? Choose the default region for your skill:  us-east-1
? Please type in your skill name:  hosted2
? Please type in your folder name for the skill project (alphanumeric):  hosted2



Project directory for hosted2 created at
	/Users/kakuri/test/hosted2

Lambda code for hosted2 created at
	./lambda

Skill schema and interactionModels for hosted2 created at
	./skill-package

Skill is enabled successfully.
Hosted skill provisioning finished. Skill-Id: amzn1.ask.skill.8c2c44fd-f295-4e2e-9a66-c86158326592
Please follow the instructions at https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#askcli to learn more about the usage of "git" for Hosted skill.
a483e7e143b4:test kakuri$ cd hosted2
a483e7e143b4:hosted2 kakuri$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	skill-package/

a483e7e143b4:hosted2 kakuri$ git add .
a483e7e143b4:hosted2 kakuri$ git commit -m'test'
[master 88395e6] test
 3 files changed, 78 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 skill-package/interactionModels/custom/en-GB.json
 create mode 100644 skill-package/skill.json
a483e7e143b4:hosted2 kakuri$ git push
After the code pushed, please check the deployment status
via Alexa Developer console:
https://developer.amazon.com/alexa/console/ask/build/custom/amzn1.ask.skill.8c2c44fd-f295-4e2e-9a66-c86158326592/development/en_GB
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (8/8), 1.01 KiB | 1.01 MiB/s, done.
Total 8 (delta 0), reused 0 (delta 0)
To https://git-codecommit.us-east-1.amazonaws.com/v1/repos/8c2c44fd-f295-4e2e-9a66-c86158326592
   d2f0266..88395e6  master -> master
```

**Comment by allenabc** [comment]
I don't want to appear ungrateful about getting a work around.  Thank you.  As I see it you could publish the work around somewhere in that thicket of documentation for ask cli or fix the problem in the script. Because the workflow doesn't work now I would prefer that you could add a line or two to the script and submit a pull request to eliminate the problem the users will inevitably run into.

**Comment by kakhaUrigashvili** [comment]
@allenabc I am going to close this ticket. By the design:
1) new skill with Lambda and CloudFormation deployer do not initialize git repo. We think it is outside of the ask cli scope to initialize new git repo after ask new command. it is up to a developer to do so.
2) new skill with Alexa Hosted Skill deployer does initialize git repo, since Alexa Hosted skill uses git commands for deploying the skill. It has very different flow compare to Lambda and CloudFormation deployer.
