### ISSUE TITLE
ask dialog --reply nosuchfile   has unclear message

### ISSUE THREAD

**Issue by allenabc** [alexa/ask-cli#347]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

ask dialog --reply <run file> fails with odd message

## Expected Behavior

ask dialog --replay  nosuchfile
file nosuchfile not found

## Current Behavior

:~/skill2$ ask dialog --replay  nosuchfile
[Error]: Please provide valid input for option: replay. Input value (nosuchfile) doesn't match REGEX rule ^[./]?[\w\-. /]+\.(json).
~/skill2$ 

**Also the help isn't complete**
 -r, --replay <replay>            [OPTIONAL] Specify a replay file to simulate dialog with Alexa

The replay file is required to be a .json file. 
Maybe you could relax this requirement that it ends in .json

s/b
 -r, --replay <replay>           Specify a replay file to simulate dialog with the skill. File must end in ,json

**ask dialog help and other commands have formatting problems** 
_```
For example

Usage: ask dialog [options]

simulate your skill via an interactive dialog with Alexa

Options:
  -s, --skill-id <skill-id>        [OPTIONAL] The skill ID.
  -l, --locale <locale>            [OPTIONAL] Locale value for the resource
  -g, --stage <stage>              [OPTIONAL] Stage for skill.
  -r, --replay <replay>            [OPTIONAL] Specify a replay file to simulate dialog with Alexa
  --save-skill-io <save-skill-io>  [OPTIONAL] Specify an output file to write simulation invocation requests and responses.
  -p, --profile <profile>          [OPTIONAL] Provides the ASK CLI profile to use. When you don't include this option, ASK CLI uses the
                                   default profile.
  --debug                          [OPTIONAL] Enables the ASK CLI  to show debug messages in the output of the command.
  -h, --help                       output usage information**_
```

[OPTION] isn't unnecessary, it's implied, 
for example
 -s, --skill-id <skill-id>        [OPTIONAL] The skill ID.
**s/b**
 -s, --skill-id <skill-id>        


**Output file option**

--save-skill-io <save-skill-io>  [OPTIONAL] Specify an output file to write simulation invocation requests and responses.
s/b
-output <outputfile>                   Save json formatted requests and responses


**If the output file isn't writeable catch the error don't throw a stack trace**

$ chmod -w myout 
$ ask dialog --replay  test.json --save-skill-io myout

============================================================ Welcome to ASK Dialog ============================================================
======================================== Replaying a multi turn conversation with Alexa from test.json ========================================
========================================== Alexa will then evaluate your input and give a response! ===========================================

User  > blue blue
Alexa > Welcome, you can say Hello or Help. Which would you like to try?
User  > hello
Alexa > Hello World!
User  > .quit
Thrown:
{ Error: EACCES: permission denied, open 'myout'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at DialogSaveSkillIoFile.save (/usr/local/lib/node_modules/ask-cli/lib/model/dialog-save-skill-io-file.js:41:10)
    at dialogReplView.registerQuitCommand (/usr/local/lib/node_modules/ask-cli/lib/controllers/dialog-controller/index.js:92:28)
    at REPLServer.replServer.on (/usr/local/lib/node_modules/ask-cli/lib/view/cli-repl-view.js:89:7)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
    at REPLServer.Interface.close (readline.js:397:8)
    at process.nextTick (repl.js:790:31)
    at process._tickCallback (internal/process/next_tick.js:61:11) errno: -13, syscall: 'open', code: 'EACCES', path: 'myout' }
User  >~/skill2$ 



<!--- Include full errors, uncaught exceptions, stack traces, and relevant logs. Remember to use --debug to get the full context -->
<!--- If service responses are relevant, please include any -->
<!--- If suggesting a change/improvement, explain the difference from current behavior -->

**CLI Snapshot**
If applicable, add screenshots to help explain your problem.

## Steps to Reproduce (for bugs)
<!--- Provide a self-contained, concise snippet of code -->
<!--- For more complex issues provide a repo with the smallest sample that reproduces the bug -->
<!--- Including business logic or unrelated code makes diagnosis more difficult -->

## Possible Solution
<!--- Not required, but suggest a fix/reason for the bug -->
<!--- or ideas how to implement the addition or change -->

## Your Environment and Context
<!--- Include as many relevant details about the environment where the bug was discovered -->
* ask-cli version: x.x.x
2.20.0
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by kakhaUrigashvili** [comment]
@allenabc just want to confirm what you are asking.
Remove requirement for the file to have .json extension or add to the documentations that the file needs to have .json extension, right?

I dont see any strange formatting for help option. May this specific to your shell. What shell are you using?

```
ask dialog -h
Usage: ask dialog [options]

simulate your skill via an interactive dialog with Alexa

Options:
  -s, --skill-id <skill-id>        [OPTIONAL] The skill ID.
  -l, --locale <locale>            [OPTIONAL] Locale value for the resource
  -g, --stage <stage>              [OPTIONAL] Stage for skill.
  -r, --replay <replay>            [OPTIONAL] Specify a replay file to simulate
                                   dialog with Alexa
  --save-skill-io <save-skill-io>  [OPTIONAL] Specify an output file to write
                                   simulation invocation requests and
                                   responses.
  -p, --profile <profile>          [OPTIONAL] Provides the ASK CLI profile to
                                   use. When you don't include this option, ASK
                                   CLI uses the default profile.
  --debug                          [OPTIONAL] Enables the ASK CLI  to show
                                   debug messages in the output of the command.
  -h, --help                       output usage information
```

**Comment by allenabc** [comment]
I guess it's just redundant to say

  -s, --skill-id <skill-id>        [OPTIONAL] The skill ID.
  -l, --locale <locale>            [OPTIONAL] Locale value for the resource
  -g, --stage <stage>              [OPTIONAL] Stage for skill.

when you could say for example

-s, --skill-id <skill-id>  
 -l, --locale <locale>        
 -g, --stage <stage> 

Here is what I am used to, something like this style  from various  UNIXes including Mac OS X

allen@allenComputer:/usr/bin$ ls --help
Usage: ls [OPTION]... [FILE]...
List information about the FILEs (the current directory by default).
Sort entries alphabetically if none of -cftuvSUX nor --sort is specified.

Mandatory arguments to long options are mandatory for short options too.
  -a, --all                  do not ignore entries starting with .
  -A, --almost-all           do not list implied . and ..
      --author               with -l, print the author of each file
  -b, --escape               print C-style escapes for nongraphic characters
      --block-size=SIZE      with -l, scale sizes by SIZE when printing them;
                               e.g., '--block-size=M'; see SIZE format below
  -B, --ignore-backups       do not list implied entries ending with ~
  -c                         with -lt: sort by, and show, ctime (time of last
                               modification of file status information);
                               with -l: show ctime and sort by name;
                               otherwise: sort by ctime, newest first
  -C                         list entries by columns
      --color[=WHEN]         colorize the output; WHEN can be 'always' (default
                               if omitted), 'auto', or 'never'; more info below
  -d, --directory            list directories themselves, not their contents

....

*******************************************************************************************************************************

It's a matter of style I guess.
If you disagree with me, you can close the bug as "as designed" or whatever the reason they use in your group.

**Comment by allenabc** [comment]
My apologies I put three issues in one "bug"

1. --help summary covered above

2. replay .json or not
    a. force the user to use .json extension probably against that 
    b. if you insist on using .json the help needs to change
 -r, --replay <replay>            [OPTIONAL] Specify a replay file to simulate dialog with Alexa
s./b
 -r, --replay <replay>            [OPTIONAL] Specify a replay file with a .json extension to simulate dialog with Alexa

3. Never ever ;) throw a stack trace -- 
Missing files, write locked files/directories, badly formatted files, badly formatted command lines
should return a brief, useful message

User  > blue blue
Alexa > Welcome, you can say Hello or Help. Which would you like to try?
User  > hello
Alexa > Hello World!
User  > .quit
Thrown:
{ Error: EACCES: permission denied, open 'myout'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at DialogSaveSkillIoFile.save (/usr/local/lib/node_modules/ask-cli/lib/model/dialog-save-skill-io-file.js:41:10)
    at dialogReplView.registerQuitCommand (/usr/local/lib/node_modules/ask-cli/lib/controllers/dialog-controller/index.js:92:28)
    at REPLServer.replServer.on (/usr/local/lib/node_modules/ask-cli/lib/view/cli-repl-view.js:89:7)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
    at REPLServer.Interface.close (readline.js:397:8)
    at process.nextTick (repl.js:790:31)
    at process._tickCallback (internal/process/next_tick.js:61:11) errno: -13, syscall: 'open', code: 'EACCES', path: 'myout' }
User  >~/skill2$

**Comment by kakhaUrigashvili** [comment]
@allenabc 

1 - it is by design. this description is shared with other commands and also used to generate some docs. I won't able to remove it. https://github.com/alexa/ask-cli/blob/develop/lib/commands/option-model.json#L40 
2 and 3 - I will fix it.

**Comment by allenabc** [comment]
command line formatting literally for decades has been like this from ls.

  ls  -a   --all do not ignore files starting with .

Your style would be this

ls  -a   --all  [ OPTIONAL] all means do not ignore files starting with .


Obviously I can't ask you to change it, you may have your reasons. It's just not industry standard. 

+++++++++++++++++++++++++++++++

As far as the run file is concerned. I would rather not type out runScript.json or test.json. I know it makes a json formatted file. One option would be to automatically append ".json" if the user doesn't add it. My preference is let the user choose the filename and leave it alone. Less typing later on.
