### ISSUE TITLE
[ask-cli v2] After git push origin master, message The master branch of your skill is ahead of the dev version on Alexa console

### ISSUE THREAD

**Issue by xarques** [alexa/ask-cli#355]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior

After the commit and push of my changes, I should see the modification on the developer console (folder Code) and I should be able to edit and modify the code through the  developer console

## Current Behavior
With ASK CLI v2.20.0 I want to clone an existing skill, then modify it and push my modifications : 

`ask init --hosted-skill-id amzn1.ask.skill.d30e42e6-0a16-4e43-809a-00f5a851d123`
Then I modify some files in the lambda directory and
`git add .`
`git commit -m 'Change backend'`
`git push origin master`
```
After the code pushed, please check the deployment status
via Alexa Developer console:
https://developer.amazon.com/alexa/console/ask/build/custom/amzn1.ask.skill.d30e42e6-0a16-4e43-809a-00f5a851d123/development/fr_FR
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (10/10), 2.94 KiB | 2.94 MiB/s, done.
Total 10 (delta 2), reused 0 (delta 0), pack-reused 0
To https://git-codecommit.us-east-1.amazonaws.com/v1/repos/d30e42e6-0a16-4e43-809a-00f5a851d123
   9236d91..d10ed82  master -> master
```
Then I go to the develop console, folder Code and there is a warning message:

**_The master branch of your skill is ahead of the dev version. To re-enable the code editor, you need to use the ASK CLI to merge the remote master branch to dev and push._**

<img width="1472" alt="Screenshot 2020-12-07 at 11 06 12" src="https://user-images.githubusercontent.com/9682473/101337832-71b94700-387c-11eb-8581-f884acdbd6b9.png">

I cannot edit my files anymore

As explained in the CLI V2 documentation, there is no more develop branch, only master and prod. So I don't understand this message and how to fix it

I tried also 
```
ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

[Warn]: Alexa hosted skills can be deployed by performing a git push.
The master branch gets deployed to skill's development stage
The prod branch gets deployed to skill's live stage
Please run "git push" at the proper branch to deploy hosted skill to your targeted stage.
```
But the issue is still present

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: 2.20.0
* Operating System and version: MacOS Catalina 10.15.7
* Node.js version used for development: v14.15.0
* NPM version used for development: 6.14.8

**Comment by kakhaUrigashvili** [comment]
@xarques yes. it is very confusing how it is designed.

prod branch -> live stage
master branch -> development stage
dev branch -> dev console

click deploy merges from dev to master
click promote live merges from master to prod.

I was able to fix the issue using the following git commands

```
git checkout dev
git pull --rebase
git merge master
# fix any merge conflict if you have any
git push --no-verify
```

**Comment by xarques** [comment]
@kakhaUrigashvili , thanks for the answer. It works now. 
The documentation [Create an Alexa-hosted skill with the ASK CLI v2](https://developer.amazon.com/en-US/docs/alexa/hosted-skills/alexa-hosted-skills-ask-cli.html#create-an-alexa-hosted-skill-with-the-ask-cli-v2) should be improved because there is no explicit reference to `dev` branch for ASK CLI V2.

**Comment by kakhaUrigashvili** [comment]
@xarques I have created a request to add information to https://developer.amazon.com/en-US/docs/alexa/hosted-skills/alexa-hosted-skills-ask-cli.html#create-an-alexa-hosted-skill-with-the-ask-cli-v2

**Comment by rapaccinim** [comment]
Thanks @kakhaUrigashvili, your solution worked perfectly for me!

**Comment by yedubi** [comment]
This is an intermediate state of the code for Alexa where you my have just pushed your current master branch. Wait a while and refresh the page. It should be in deploying state after a few minutes.
