### ISSUE TITLE
Feature: Refreshing the access_token via CLI

### ISSUE THREAD

**Issue by asarazan** [alexa/ask-cli#358]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior
I would love to be able to call something like `ask token get` to emit the token currently in `~/.ask/cli_config`, and call `ask token refresh` to automatically use the `refresh_token` on that file to update it with a new `access_token`.

## Current Behavior
From what I can tell, all that's currently supported is `ask util generate-lwa-tokens`, which necessarily has a blocking web component, even when a valid refresh token is present. This makes it difficult for automating flows (in this case we're trying to build tooling around `ask-sdk-local-debug`).

## Your Environment and Context
* ask-cli version: 2.15.0
* Operating System and version: OSX 10.15.7
* Node.js version used for development: v12.16.1
* NPM version used for development: 6.13.4

**Comment by kakhaUrigashvili** [comment]
@asarazan what is your use case around build tooling for ask-sdk-local-debug? Just want to make sure it is not similar to https://github.com/alexa/ask-cli/pull/325

**Comment by asarazan** [comment]
Actually it does appear to be quite similar. Some of our devs have been using local debugging with the ASK vscode plugin, and I'm trying to bring feature parity to our IntelliJ users. Unfortunately it has been difficult to recreate the auth magic that the VScode plugin does.

It seems like the linked PR would solve my problem in a much more convenient way, feel free to close this ticket :+1:

**Comment by nikhilym** [comment]
@asarazan  Sorry for intercepting the actual feature request here, but can we know your use case of doing this on IntelliJ instead of using the VScode plugin? Just trying to understand our skill developers a bit better. 

If it is purely for IDE preference purposes, we get it. But if it has something to do with the plugin itself, we would love to know that feedback and try to address it better.

**Comment by asarazan** [comment]
Yep I can confirm it's basically just about IDE preference. I'm trying to make sure IntelliJ remains a viable option for our engineers :-)

**Comment by nikhilym** [comment]
Understood, thanks a lot @asarazan .

**Comment by kakhaUrigashvili** [comment]
@asarazan I have tested your use case with the PR branch, you should be able to use IntelliJ with new debug command once the change is merged and deployed.
![combine_images](https://user-images.githubusercontent.com/17086971/101928336-4f7c3d80-3b8a-11eb-9df9-1f60924c7deb.jpg)
