### ISSUE TITLE
Git push origin stop working

### ISSUE THREAD

**Issue by xavidop** [alexa/ask-cli#359]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe: 
</code></pre>

After upgrading to ASK CLI 2.21.0 from ASK CLI 2.15.0 the git push origin master for alexa hosted start failing using environment variables.

## Expected Behavior
It should work like the older versions.

## Current Behavior
Now it throws an error with this output:

'/home/node/.ask/scripts/git-credential-helper' __ENVIRONMENT_ASK_PROFILE__ amzn1.ask.skill.19a120ae-2560-4711-af91-556262cf7f63 get: line 1: /home/node/.ask/scripts/git-credential-helper: not found
Username for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/19a120ae-2560-4711-af91-556262cf7f63': fatal: could not read Username for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/19a120ae-2560-4711-af91-556262cf7f63': No error information

Note: ask new command works fine.

## Steps to Reproduce (for bugs)
run a git push origin master of an Alexa Hosted Skill using **ENVIRONMENT VARIABLES**

## Possible Solution
Check if you are running in enviaronment variables mode and download all the scripts.

## Your Environment and Context
* ask-cli version: 2.21.0
* Operating System and version: Linux
* Node.js version used for development: 12.18.0
* NPM version used for development: 6.14.16

**Comment by kakhaUrigashvili** [comment]
@xavidop can you paste output of
`cat .git/config `
here is mine
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[credential "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/34ab651d-415d-4911-9666-ca395ba6b79c"]
	helper = 
	helper = !'/Users/kakuri/.ask/scripts/git-credential-helper' __ENVIRONMENT_ASK_PROFILE__ amzn1.ask.skill.34ab651d-415d-4911-9666-ca395ba6b79c
	UseHttpPath = true
[remote "origin"]
	url = https://git-codecommit.us-east-1.amazonaws.com/v1/repos/34ab651d-415d-4911-9666-ca395ba6b79c
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "prod"]
	remote = origin
	merge = refs/heads/prod
```

**Comment by kakhaUrigashvili** [comment]
@xavidop Is it not working for new or existing skill? I tried and it worked for me doing this.
```
ask new
cd skill-folder
git add .; git commit -m'test'; git push
```

**Comment by xavidop** [comment]
It is not running for any alexa skill that has not been created with the ask new command

**Comment by kakhaUrigashvili** [comment]
@xavidop what if you use init command?
`ask init --hosted-skill-id your-existing-hosted-skill-id`

**Comment by xavidop** [comment]
Will That command create the missing scripts folder?

**Comment by kakhaUrigashvili** [comment]
@xavidop yes. it should.

**Comment by xavidop** [comment]
Are any command that only download that scripts? In 2.15.0 and older versions we do not have these dependencies...

**Comment by kakhaUrigashvili** [comment]
@xavidop there is not command to download scripts separately. 

"older versions we do not have these dependencies..." -agree. adding extra unnecessary dependencies can sometimes cause issues. 

Here is location of those scripts: https://github.com/alexa/ask-cli/blob/develop/lib/utils/dynamic-config.js#L37. Disclosure: it would be a backdoor and not officially supported. The long term: I can discuss with the team about providing a way to download scripts or some other option to mitigate this issue.

**Comment by xavidop** [comment]
The problem that I have is that in my case, I am using CricleCI so in one step I create the Alexa Skill with ask new command and in another step I push some modifications. There .ask folder it is not shared between steps becuase it was not necessary before. That could be happening to more customers.

**Comment by xavidop** [comment]
FYI, sharing the .ask folder at the time of the creation of the skill during all the pipeline turns green again the CircleCI status.
