### ISSUE TITLE
dialog command complain wrong message

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#361]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Current Behavior

Wrong message is being displayed in dialog command in this [code](https://github.com/alexa/ask-cli/blob/develop/lib/commands/dialog/index.js#L109-L112).`skillId` is not stored in ask-resources.json.

## Possible Solution

Update the message to suggest user to deploy the skill

**Comment by doiron** [comment]
fix has been merged and released v2.29.1 

thank you for reporting
