### ISSUE TITLE
Refactor with ask-smapi-sdk

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#362]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[x] Other... Refactor
</code></pre>

## Expected Behavior
Using ask-smapi-sdk (https://www.npmjs.com/package/ask-smapi-sdk) should be happening in the smapi-client.

## Current Behavior
Currently the smapi-client is stored in the code. Relying on ask-smapi-sdk saves us effort to maintain new APIs.

## Possible Solution
Notes:
1. Smapi-sdk doesn't support same existing env var as CLI does. `ASK_REFRESH_TOKEN` `ASK_ACCESS_TOKEN` and `ASK_CLI_PROXY` are all supported settings in current ask-cli. We need to pass those data to smapi-sdk as well
2. The support for network trace (enabled when --debug is set) should be identical to what we have.

**Comment by CamdenFoucht** [comment]
Smapi client was refactored in ask-cli-x and will be released in a later cli version.
