### ISSUE TITLE
ASK Deploy not working when using existing Lambda ARN

### ISSUE THREAD

**Issue by paul-uz** [alexa/ask-cli#364]
I created a fresh "blank" lambda function (not entirely empty, as it creates the Hello World example)

I modified my Alexa project to point to the ARN, and I attached the Alexa Skill ID to the Function.

When running `ask deploy` I get this:

```
[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": AlexaSkillFunction[AWS::Lambda::Function]  CREATE_FAILED (arn:aws:lambda:eu-west-1:128286298034:function:AlexaTest already exists)
```

Why is it trying to make a new function? I have specified the ARN in the configuration files.

skill-stack.yml

```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SkillId:
    Type: String
  LambdaRuntime:
    Type: String
  LambdaHandler:
    Type: String
  LambdaName:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String
Resources:
  AlexaSkillIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: alexaSkillExecutionPolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:*
                  Resource: arn:aws:logs:*:*:*
  AlexaSkillFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt AlexaSkillIAMRole.Arn
      MemorySize: 512
      Timeout: 60
  AlexaSkillFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-appkit.amazon.com
      EventSourceToken: !Ref SkillId
  AlexaSkillFunctionEventPermissionSmartHome:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-connectedhome.amazon.com
      EventSourceToken: !Ref SkillId
  AlexaSkillFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlexaSkillFunction}
      RetentionInDays: 14
Outputs:
  SkillEndpoint:
    Description: LambdaARN for the regional endpoint
    Value: !GetAtt AlexaSkillFunction.Arn
```

skill.json

```
...
    "apis": {
      "custom": {
        "endpoint": {
          "uri": "arn:aws:lambda:eu-west-1:128286298034:function:AlexaTest"
        }
      }
    },
...
```

ask-resource.json

```
{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillMetadata": {
        "src": "./skill-package"
      },
      "code": {
        "default": {
          "src": "./lambda"
        }
      },
      "skillInfrastructure": {
        "type": "@ask-cli/cfn-deployer",
        "userConfig": {
          "runtime": "nodejs10.x",
          "handler": "index.handler",
          "templatePath": "./infrastructure/cfn-deployer/skill-stack.yaml",
          "awsRegion": "eu-west-1",
          "cfn": {
            "parameters": {
              "LambdaName": "arn:aws:lambda:eu-west-1:128286298034:function:AlexaTest"
            }
          }
        }
      }
    }
  }
}
```

why is the ASK CLI so darn unintuitive and difficult to use?! I just want to deploy code to an exisitng function and skill!

EDIT - I deleted the function, and tried to deploy, now I get 

```
[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": AlexaSkillFunctionEventPermission[AWS::Lambda::Permission]  CREATE_FAILED (Resource creation cancelled)
```

FML

**Comment by paul-uz** [comment]
Looks like there is an issue with the provided CF YML file. I am seeing this error in the event list,

```
Model validation failed (#/LogGroupName: failed validation constraint for keyword [pattern])
```

Which relates to (unedited)

```
AlexaSkillFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlexaSkillFunction}
      RetentionInDays: 14
```

Removing the `LogGroupName` now means deployment finishes successfully.

**Comment by kakhaUrigashvili** [comment]
@paul-uz LambdaName is just a parameter passed to CloudFormation template. ask cli does not do any magic about it. The error, you are seeing  is from the CloudFormation. If you want to provide lambda arn you can modify the CloudFormation template to accept Lambda ARN and add this parameter to ask-resources.json.

What should be an action item on the ask cli side for this issue?

**Comment by paul-uz** [comment]
@kakhaUrigashvili can you explain why I cannot create an empty Lambda function and use that ARN in my new skill configs?

As mentioned, I had to let Cloudformation create it. Ideally, if the lambda function already exists, i should be able to use it regardless.

**Comment by kakhaUrigashvili** [comment]
@paul-uz I don't seen an option to specify Lambda Arn in the CloudFormation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

You can pass Lambda Arn as parameter without creating new lambda but then the Lambda won't be update by 'ask deploy'

The CloudFormation needs to create the Lambda in order manage it.

Are you able to just copy your existing lambda and put the into lambda folder?

`aws lambda get-function --function-name arn:aws:lambda:us-east-1:200074948102:function:ask-node-skill-default-default-1608223548393 --region us-east-1`

https://docs.aws.amazon.com/cli/latest/reference/lambda/get-function.html

**Comment by RonWang** [comment]
Pls feel free to reopen if you have further question!
