### ISSUE TITLE
Cannot deploy skill to new Cloudformation Stack / Lambda Function / Skill

### ISSUE THREAD

**Issue by paul-uz** [alexa/ask-cli#365]
I have a working skill project, that I was successfully deploying to this afternoon.

Now, I want to deploy this same project to a new Cloudformation Stack (with new Lambda Function and new Alexa Skill Project)

I ran `ask init` and it wanted to override the `ask-resource.json` file, ok no biggy.

But when trying to do `ask deploy` it fails with `The trigger setting for the Lambda ... is invalid`

This seems to be because the Lambda Function does not have the Skill Trigger with ID configured... Because the Lambda does not exist yet... Because I'm deploying afresh...

Seriously, what is going on here? Why is this so entirely backwards and difficult to figure out?

I just want to deploy my working skill project to a new stack.

EDIt - I just tried manually creating the Skill and Lambda Functions, adding the trigger, entering the SKill ID and using the ARN in the CFN deploy config, but I get the same error about the trigger being invalid.

**Comment by kakhaUrigashvili** [comment]
@paul-uz to deploy the same project to with with new Lambda Function and new Alexa Skill Project.

1) delete .ask/ask-states.json
2) delete from skill-package/skill.json. manifest->apis->custom->endpoint
3) ask deploy

Additionally, if you want to reuse the project, you can push to some git repo and use it as a template

`ask new --template-url <template-url>  --template-branch <template-branch>`

**Comment by paul-uz** [comment]
@kakhaUrigashvili but I cannot set a custom ARN for the first deploy correct? I think this was said before, and that is obv a limitation.

I just managed to deploy a new stack, and afterwords changed the ARN to a custom new name, and that seems to work.

Please let `ask deploy` using CFN deployer create new ARNs with a custom name 🙏

**Comment by kakhaUrigashvili** [comment]
@paul-uz 
You can set lambda name for the first deploy. You cannot set lambda arn explicitly regardless if it is first or not deploy, since it is not a property that CFN supports.

Did this solution work for you https://github.com/alexa/ask-cli/issues/336#issuecomment-750357310 ?

**Comment by paul-uz** [comment]
Sorry but I don't think you are right.

First, I tried putting custom name ( it ARN) and that did not work.

Then, after eventually managing some how to get a new stack created, I
changed the lambda name putting full ARN in json file, and it deployed and
made a new lambda function for me.

I'm also still confused by ask-states.json and if it should be in git, as
people have given different answers.

For cfn deployer, using custom lambda skill, should that file be in git? It
seems to be the only config that has the skill ID?

**Comment by paul-uz** [comment]
@kakhaUrigashvili I did what you suggested, and got this error when trying to run `ask deploy`

```
            "message": "Object instance at property path \"$.manifest.apis\" has no property defined."
```

I deleted `ask-states.json` and removed custom API endpoint from `skill.json`

**Comment by kakhaUrigashvili** [comment]
@paul-uz 

You should not need to set endpoint property yourself, ask cli sets it during the deploy command.

Make sure skill-package/skill.json has empty placeholder like "custom" (custom skill for example). This should be default for a new project.

```
....
      "apis": {
        "custom": {}
      },
....
```
After ask deploy, it should look something like 
```
"apis": {
      "custom": {
        "endpoint": {
          "uri": "arn:aws:lambda:us-east-1:200074948102:function:my-custom-name"
        }
      }
    },
```

**Comment by paul-uz** [comment]
@kakhaUrigashvili I am somewhat able to get this working now.

I have just tried deploying to a fresh skill + lambda function, and I am getting this error:

```
{
  "message": "Skill is not ready for enablement.",
  "violations": [
    {
      "message": "Custom skills must have an interaction model."
    }
  ]
}
```

I have only made minor changes to the interaction model eg slot values. The JSON looks valid and my IDe is not showing any errors.
