### ISSUE TITLE
Cannot upgrade alexa ask v1 to v2

### ISSUE THREAD

**Issue by stormsa** [alexa/ask-cli#367]
## Cannot upgrade ask v1 to ask v2

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

Hello I try to upgrade my nodejs alexa project from ask v1 to ask v2 with the command : 
````
ask util upgrade-project --debug
`````
But the command finally throw the following error  : 
request-id: d96b1552-de81-4095-b7cd-2b16498a59cc
POST https://api.amazonalexa.com/v1/skills/amzn1.ask.skill.f3d248ea-5d09-4863-b387-ef04cdb17ab9/stages/development/exports
status code: 500 Internal Server Error

Response headers: {"content-type":"application/json","content-length":"36","connection":"close","server":"Server","date":"Sun, 27 Dec 2020 14:55:53 GMT","x-amz-rid":"6PNMZBNGF1D9V740HXVV","x-amzn-requestid":"af0b4a33-1314-49a0-918d-629f6cd2e414","x-amz-date":"Sun, 27 Dec 2020 14:55:53 GMT","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","x-cache":"Error from cloudfront","via":"1.1 ae1b2f64d909bc787f8b2cb1e91446cd.cloudfront.net (CloudFront)","x-amz-cf-pop":"CDG53-C1","x-amz-cf-id":"07bMgPa5GJq-E8xxG6182rYu776p2DCu8MLQkmNYs5hcY71otjaJgQ=="}

I don't understand why this error happened. 

## Your Environment and Context

* ask-cli version: 2.22.0
* Operating System and version: MAC OS
* Node.js version used for development: v12.18.2
* NPM version used for development: 6.14.8
* lambda runtime : nodejs8.10
* awsRegion : eu-west-1
* function : ask-custom-quiz-islam-default

Thank you very much for your support.

**Comment by stormsa** [comment]
To pass through the problem, I used ask init command and I set my skill id. 
But if you still found the issue for the next developer it will be great :)

**Comment by kakhaUrigashvili** [comment]
@stormsa looks like it should throw error if the skill id is not present 
https://github.com/alexa/ask-cli/blob/develop/lib/commands/util/upgrade-project/helper.js#L61

Did you have skillId in .ask/config?

**Comment by RonWang** [comment]
We've passed your case to our service team. Please feel free to re-open this issue by replying the question, then we will further help with your case.
