### ISSUE TITLE
ASK CLI Java Hello World example fails without logging errors

### ISSUE THREAD

**Issue by TDA** [alexa/ask-cli#370]
Hey,
Using the ASK CLI to create a Java Hello World skill fails all invocations by default and needs me to bump up the Lambda memory to 364+Mb to get the skill to start working. The reason for failure is also not printed out for the Hello World skill but its printed out correctly for the Fact skill --- I think I know why its not getting printed for the Hello World skill while the error is printed out for the Fact skill.

Steps to reproduce:
1. `ask new`. 
  ```
  Choose the programming language you will use to code your skill:  Java
  Choose a method to host your skill's backend resources:  AWS Lambda
  Host your skill code on AWS Lambda (requires AWS account).
  Choose a template to start with:  Hello World
  ```
2. `cd` into the folder, and do `ask deploy`
3. Go to ADC and Test your skill with the invocation utterance. e.g. "open hello world"
4. Expected Response: "Hello World"
5. Actual Response: "There was a problem with the requested skill's response"
6. Lambda logs show no errors.

I then tested with the `fact skill template`, and the steps are almost the same:
1. `ask new`. 
  ```
  Choose the programming language you will use to code your skill:  Java
  Choose a method to host your skill's backend resources:  AWS Lambda
  Host your skill code on AWS Lambda (requires AWS account).
  Choose a template to start with:  Fact skill
  ```
2. `cd` into the folder, and do `ask deploy`
3. Go to ADC and Test your skill with the invocation utterance. e.g. "open airplane facts"
4. Expected Response: "Welcome to airplane ..."
5. Actual Response: "There was a problem with the requested skill's response"
6. Lambda logs this time show an error: `Exception in thread "main" java.lang.Error: java.lang.OutOfMemoryError: Metaspace`

Googled and found that Bumping up the memory fixes this. Tried a bunch of combinations and found that moving it to anything more than 364mb fixes it. Then I got to figuring out why this wasnt getting printed in the `Hello World` example. Turns out, `Hello World` example takes a dependency on ASK-SDK 2.20.2, while the `Fact skill` example takes a dependency on ASK-SDK 2.5.5.

ASK-SDK 2.5.5 for some reason prints the error while 2.20.2 does not. 

Fixes needed:
1. Make the CFN templates for Lambda to specify at least 364mb (or whatever the minimum is) so that the skills work by default. This fix is needed in this package. If this is not possible, proceed to 2.
2. Communicate to ASK-SDK team that some change between 2.5.5 and 2.20.2 broke their error reporting mechanism and OutOfMemory errors are no longer getting printed to CloudWatch from Lambda on 2.20.2. This makes it insanely hard to figure out the OOTB experience is failing.

Tagging SDK team member @sattpat for visibility.

**Comment by kakhaUrigashvili** [comment]
@TDA opened PR https://github.com/alexa/ask-cli/pull/371

**Comment by TDA** [comment]
Thanks for doing this @kakhaUrigashvili ! Do we need to create a separate issue with the SDK team to track the changes for the error reporting fix, or can we loop in someone from there on this issue?

**Comment by kakhaUrigashvili** [comment]
@TDA

1) ask sdk is on **2.37.1**
https://github.com/alexa/alexa-skills-kit-sdk-for-java/blob/2.0.x/ask-sdk/pom.xml#L7
Have you tested with 2.37.1 to see if the same issue exists? If exists, I would open issue for alexa-skills-kit-sdk-for-java repo.

2) The template we use for the hello world is on **2.20.2** of ask sdk
https://github.com/RonWang/skill-sample-java-premium-hello-world/blob/ask-cli-x/lambda/pom.xml#L34

Other templates also on lower versions.

@RonWang should the hello world template be updated & moved under Alexa org?





https://ask-cli-static-content.s3-us-west-2.amazonaws.com/skill-templates/java-templates.json

**Comment by kakhaUrigashvili** [comment]
@TDA I have deployed new ask cli version(2.22.3) to address the timeout issue.

Please open PR for the template repo to fix logging issue.
