### ISSUE TITLE
Feature Request: Skill Account Linking Update During Deployment

### ISSUE THREAD

**Issue by jsetton** [alexa/ask-cli#374]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior
It would great if having the ability to automatically update the skill account linking config, during the deployment process, when a file (e.g. `skillPackage/accountLinking.json`) containing the [account linking request schema](https://developer.amazon.com/en-US/docs/alexa/smapi/account-linking-schemas.html) is present and valid.

**Comment by kakhaUrigashvili** [comment]
@jsetton Thank you for feature request.

I think this should be supported by the server side, as part of the skill package, for consistency.

https://developer.amazon.com/en-US/docs/alexa/smapi/skill-package-api-reference.html

"Your skill might also contain account linking information, which is currently not supported by the Skill Package API. You can still use the Skill Package API, but you will also have to use SMAPI to manage account linking."

**Comment by jsetton** [comment]
>  think this should be supported by the server side, as part of the skill package, for consistency.

@kakhaUrigashvili I agree. I am not sure why it is not supported in the Skill Package API. My request was to fill that gap at the CLI level.

**Comment by kakhaUrigashvili** [comment]
@jsetton I dont think we are going to support it on the CLI level. You possibly can create bash script to add additional actions to the deploy flow.

`
ask deploy
ask smapi update-account-linking-info
`
