### ISSUE TITLE
Old powershell Compress-Archive not compatible with AWS

### ISSUE THREAD

**Issue by desiderataaus** [alexa/ask-cli#38]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

askx deployed skill will throw load exception. It seems that the dependent files are not in the right place. The root cause is zip file generated by PowerShell is not compatible with other operating systems.

## Expected Behavior

There should be a node_module folder under lambda function source tree.

## Current Behavior

See screenshot below

**CLI Snapshot**
![image](https://user-images.githubusercontent.com/5094582/69106626-14acf080-0ac3-11ea-9a6e-4800e2e5901e.png)

## Steps to Reproduce (for bugs)

1. Open Powershell window
1. askx new and follow the promting
1. askx deploy

## Possible Solution

```
Install-Module Microsoft.PowerShell.Archive -MinimumVersion 1.2.3.0 -Repository PSGallery -Force
```

See the issue and solution [here](https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/71).

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version: windows 10 Enterprise
* Node.js version used for development: 10.16
* NPM version used for development: 6.9.0

**Comment by Shreyas-vgr** [comment]
Hi @desiderataaus, Thanks for raising the issue and pointing out the possible solution, we will work on releasing a fix soon.

**Comment by RonWang** [comment]
We update our [FAQ](https://github.com/alexa/ask-cli/blob/develop/docs/FAQ.md#q-for-windows-users-if-your-skill-return-empty-response-and-log-shows-module-not-found-genericerrormapper-or-cannot-find-module-dispatchererrormappergenericerrormapper-how-to-resolve) to reflect this Powershell problem. Close this issue.
