### ISSUE TITLE
ask new succeeds but next steps seem to be missing and documentation is missing

### ISSUE THREAD

**Issue by allenabc** [alexa/ask-cli#393]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

After running "ask new" I am asked to get information about a git attribute that has no relevancy to "ask new"

## Expected Behavior
I assume you can run "ask run" sometime but I can't get it to work

## Current Behavior
After "ask new" completes successfully I am told to get more information about git. 

https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#askcli

There isn't any useful/relevant information about using git on this page.

**CLI Snapshot**

## Steps to Reproduce (for bugs)
run "ask new" wait for it to complete

$ ask new 
Please follow the wizard to start your Alexa skill project ->
? Choose the programming language you will use to code your skill:  NodeJS
? Choose a method to host your skill's backend resources:  Alexa-hosted skills
  Host your skill code by Alexa (free).
? Choose the default region for your skill:  us-east-1
? Please type in your skill name:  First Skill
? Please type in your folder name for the skill project (alphanumeric):  FirstSkill

Project directory for First Skill created at
        /home/allen/Alexa_skills/FirstSkill

Lambda code for First Skill created at
	./lambda

Skill schema and interactionModels for First Skill created at
	./skill-package

Skill is enabled successfully.

Hosted skill provisioning finished. Skill-Id: amzn1.ask.skill.6a17c596-9357-47df-adbc-97c5586dd99e
Please follow the instructions at https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#askcli to learn more about the usage of "git" for Hosted skill.
$ 

## Possible Solution

After running ask new there should be useful information like you can now run "ask deploy" or "ask run"
Please don't suggest that I create skills from the Web-page alexa developer console.

My expectation is that the ask "cli" tool should run end to end from creating a skill to running a skill. Didn't get past ask new. The skill did show up in the Web UI waiting to be deployed. ask deploy didn't work

Here is the dialog. git push is run nothing seems to happen

 $ ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

[Warn]: Alexa hosted skills can be deployed by performing a git push.
The master branch gets deployed to skill's development stage
The prod branch gets deployed to skill's live stage
Please run "git push" at the proper branch to deploy hosted skill to your targeted stage.

$ git push
After the code pushed, please check the deployment status
via Alexa Developer console:
https://developer.amazon.com/alexa/console/ask/build/custom/amzn1.ask.skill.6a17c596-9357-47df-adbc-97c5586dd99e/development/en_US
Everything up-to-date

$ ask deploy
Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

[Warn]: Alexa hosted skills can be deployed by performing a git push.
The master branch gets deployed to skill's development stage
The prod branch gets deployed to skill's live stage
Please run "git push" at the proper branch to deploy hosted skill to your targeted stage.
$ 

## Your Environment and Context

* ask-cli version: 2.22.4
* Operating System and version: Ubuntu 20.04.2 LTS
* Node.js version used for development:15.4.0
* NPM version used for development: 7.10.0

**Comment by bbezerra82** [comment]
Created [pull request](https://github.com/alexa/ask-cli/pull/396) to update the string.

**Comment by spkai** [comment]
Hi @allenabc, for git-managed hosted skills, `git push origin master` should also update your development version of the skill if there are code changes. Updated docs are [here](https://developer.amazon.com/en-US/docs/alexa/hosted-skills/alexa-hosted-skills-ask-cli.html). You can test your skill from the built-in simulator `ask dialog --locale en-US`.

Closing for now, feel free to re-open if you had more questions!
