### ISSUE TITLE
Broken link for ask-cli-telemetry return 404 Page not found

### ISSUE THREAD

**Issue by emanuelb** [alexa/ask-cli#395]
Visiting the link in postinstall message: https://developer.amazon.com/docs/alexa/smapi/ask-cli-telemetry.html return 404 
Page not found.
https://github.com/alexa/ask-cli/blob/54f972b185ea989c97fc667a83b320f84c2b65de/postinstall.js#L7

**Comment by CamdenFoucht** [comment]
Hi @emanuelb Thank you for letting us know the link isn't working. I will look into it

**Comment by doiron** [comment]
The link was fixed last spring/summer.   Please feel free to re-open if the issue persists.
