### ISSUE TITLE
Error: invalid_scope when using ask-confugure

### ISSUE THREAD

**Issue by diana-tchalakova** [alexa/ask-cli#398]
Hello,

I am getting an error:
`[Error]: Error: invalid_scope
Reason: An unknown scope was requested`

when trying to configure a new profile (ask configure) with the following URL:

`https://www.amazon.com/ap/oa?response_type=code&client_id=CLIENT_ID3427&state=Ask-SkillModel-ReadWrite&scope=alexa%3A%3Aask%3Askills%3Areadwrite%20alexa%3A%3Aask%3Amodels%3Areadwrite%20alexa%3A%3Aask%3Askills%3Atest%20alexa%3A%3Aask%3Acatalogs%3Aread%20alexa%3A%3Aask%3Acatalogs%3Areadwrite%20alexa%3A%3Aask%3Asubscriptions%20alexa%3A%3Aask%3Askills%3Adebug&redirect_uri=https%3A%2F%2Fask-cli-static-content.s3-us-west-2.amazonaws.com%2Fhtml%2Fask-cli-no-browser.html
`

(Note that I removed the client id from the above request; the client ID is not the default one).

This command was working a week ago (May 11) without any problems. We haven't changed the client id since then.

**Comment by CamdenFoucht** [comment]
Hi @diana-tchalakova, have you had any more problems with this command? I was not able to reproduce so I will close this issue for now. But please reopen if you are still facing it.
