### ISSUE TITLE
Custom templates from Git branch/tag and/or path

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#40]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When creating a new project from a custom template I would like to be able to specify a branch/tag and/or path within the Git repository. This enables me to have various versions of a project template (when specifying a branch/tag) or multiple templates within a given repository (if specifying a path).

## Current Behavior

Currently, `ask new` simply clones an entire repository from `master` and `askx new` clones an entire repository from the `ask-cli-x` branch.

**Comment by RonWang** [comment]
Hi @habuma ,

Thanks for your great feature request, we will definitely work on how to expand the URL options for `askx new` command as we also have considered this feature. In the meantime, do you have a solid example of this usage? If not this feature request will be a relatively low-priority one for us, and please use this open issue to track the status later.

Thanks,
Ron

**Comment by RonWang** [comment]
We will consider to add the option `--template-branch` to the "ask new" command.

**Comment by kakhaUrigashvili** [comment]
Opened PR: https://github.com/alexa/ask-cli/pull/155

**Comment by kakhaUrigashvili** [comment]
@habuma added --template-branch option in version 2.4.0
