### ISSUE TITLE
ask dialog [Error]: "Invalid request payload. Please ensure that the request payload has no invalid fields"

### ISSUE THREAD

**Issue by kevinseq1** [alexa/ask-cli#405]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior
The `ask dialog` command as shown in the [README.md](https://github.com/alexa/ask-cli/blob/develop/README.md) helps to interact with the skill.

## Current Behavior
The `ask dialog` command as shown in the [README.md](https://github.com/alexa/ask-cli/blob/develop/README.md) does not behave like its supposed and gives the following error when following instructions from [README.md](https://github.com/alexa/ask-cli/blob/develop/README.md):
```
User  > open hello world
[Error]: {
  "message": "Invalid request payload. Please ensure that the request payload has no invalid fields"
}
User  > 

```

**Comment by RonWang** [comment]
Hey @kevinseq1  thanks for reporting this issue! We are addressing it and will get back with the fix.

**Comment by RonWang** [comment]
Closing this issue and please check out the fix at https://www.npmjs.com/package/ask-cli/v/2.24.1. Let us know if there's still a problem
