### ISSUE TITLE
Documentation: Add AWS credentials Policy Permissions For CFN Deployer

### ISSUE THREAD

**Issue by jsetton** [alexa/ask-cli#408]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Current Behavior
The official documentation related to creating AWS credentials to use with ASK CLI is missing the policy permissions necessary to use the CFN deployer.

https://developer.amazon.com/en-US/docs/alexa/smapi/manage-credentials-with-ask-cli.html#create-aws-credentials

## Proposed Change
```json
{
  "Version": "2012-10-17",
  "Statement": {
    "Effect": "Allow",
    "Action": [
      "cloudformation:CreateStack",
      "cloudformation:UpdateStack",
      "cloudformation:DescribeStacks",
      "cloudformation:DescribeStackResource",
      "cloudformation:DescribeStackResources",
      "iam:CreateRole",
      "iam:GetRole",
      "iam:AttachRolePolicy",
      "iam:PassRole",
      "lambda:AddPermission",
      "lambda:CreateFunction",
      "lambda:GetFunction",
      "lambda:UpdateFunctionCode",
      "lambda:UpdateFunctionConfiguration",
      "lambda:ListFunctions",
      "logs:FilterLogEvents",
      "logs:getLogEvents",
      "logs:describeLogStreams",
      "s3:CreateBucket",
      "s3:ListBucket",
      "s3:GetBucketVersioning",
      "s3:PutBucketVersioning",
      "s3:GetObject",
      "s3:PutObject"
    ],
    "Resource": "*"
  }
}
```

**Comment by CamdenFoucht** [comment]
Than you for the proposed change, I will reach out and get the documentation updated!

**Comment by jsetton** [comment]
@CamdenFoucht any chance the documentation will get updated?

**Comment by CamdenFoucht** [comment]
Sorry for the lateness, the doc has been updated: https://developer.amazon.com/en-US/docs/alexa/smapi/manage-credentials-with-ask-cli.html#create-aws-credentials

Thank you!!
