### ISSUE TITLE
Error while converting Alexa Skill into ACDL based skill, askx decompile command throws error

### ISSUE THREAD

**Issue by theguaz** [alexa/ask-cli#412]
ASK CLI error thrown while following this tutorial:
https://developer.amazon.com/en-US/docs/alexa/conversations/acdl-tutorial-convert-skill.html

### Expected Behavior
Decompile ACIR files to ACDL files on action local folder by running command at step 2 of the tutorial:
`askx decompile` 

### Current Behavior
Getting an undocumented error like this:
`[Error]: invalid ASK Module: '/Users/me/Documents/ACDL-FinalAlexa/skill-package/conversations/dialogs.json'`

We also uninstalled **ask-cli**, installed it back and also did upgrade on it with no results.

**Comment by CamdenFoucht** [comment]
Hi @theguaz are you still facing this error? This error means the ASKIR had an improper schema. Would you be able to share the ASKIR file?

**Comment by doiron** [comment]
closing due to no response. Please re-open the issue with the ASKIR file in question.  thanks
