### ISSUE TITLE
ask new (with all defaults) fails

### ISSUE THREAD

**Issue by fwornle** [alexa/ask-cli#413]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

Creation of new skill project, hosted on Alexa ("Hello World"), fails. The command returns with:
[Error]: Error: getaddrinfo ENOTFOUND ask-tools-core-content.s3-us-west-2.amazonaws.com

Not sure what I can do to get "Hello World" to run. I am using ASK version 2.24.1 and have linked it to my Developer Account **without linking it to my AWS account** (as this has been reported to fail, see [issue 401](https://github.com/alexa/ask-cli/issues/401))

## Expected Behavior
Initialization of a "hello world" skill with all defaults (as suggested in the documentation) does not fail.

## Current Behavior
Initialization of a "hello world" skill with all defaults (as suggested in the documentation) fails:

**λ** ask new
Please follow the wizard to start your Alexa skill project ->
? Choose the programming language you will use to code your skill: **NodeJS**
? Choose a method to host your skill's backend resources: **Alexa-hosted skills**
Host your skill code by Alexa (free).
? Choose the default region for your skill: **eu-west-1**
? Please type in your skill name: **Hello World**
? Please type in your folder name for the skill project (alphanumeric): **HelloWorld**
**[Error]: Error: getaddrinfo ENOTFOUND ask-tools-core-content.s3-us-west-2.amazonaws.com**

**CLI Snapshot**
![image](https://user-images.githubusercontent.com/13975765/136693698-6d86a2e7-8038-4b28-85e0-d8d39592778d.png)

## Steps to Reproduce (for bugs)
(see above)

## Your Environment and Context

* ask-cli version: 2.24.1
* Operating System and version: Win-10
* Node.js version used for development: v14.18.0
* NPM version used for development:  6.14.15

**Comment by jsetton** [comment]
You need to check your network settings and determine why your machine isn't able to resolve that address. There is most likely an issue with your local environment.
