### ISSUE TITLE
Deploy ASK project without Lambda

### ISSUE THREAD

**Issue by paul-uz** [alexa/ask-cli#417]
Currently, using the ASK CLI, it seems you must deploy the Lambda function in one way or another, either as a Cloudformation stack, the standalone Lambda, or as a hosted skill.

Is there a way to deploy just the skill config, so I can edit and deploy the Lambda separately? 

Ideally, I want to add the ASK Lambda function to a pre-exisiting stack we have, and then just tie the Alexa skill to that lambda, but I have no idea how to achieve this.

**Comment by CamdenFoucht** [comment]
Closing since @jsetton has given you the solution!
