### ISSUE TITLE
Remove deprecated local-debugger.js from Alexa-hosted skill template

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#419]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[X] Other... Please describe: Remove a deprecated feature
</code></pre>

## Expected Behavior
When creating a new project, the lambda/local-debugger.js script shouldn't be included in the new project.

## Current Behavior
Currently, when creating an Alexa-hosted skill, lambda/local-debugger.js is included. But per comments in that very same script, this script has been deprecated in favor of VSCode and ask-sdk-local-debug support.

## Steps to Reproduce (for bugs)
Perform `ask new` and create a new Alexa-hosted Node.js skill. 

## Possible Solution
Remove local-debugger.js from the Alexa-hosted skills template.

## Your Environment and Context

* ask-cli version: 2.24.1
* Operating System and version: MacOS 11.6
* Node.js version used for development: 16.6.1
* NPM version used for development: 7.24.1

**Comment by CamdenFoucht** [comment]
You are right, we will reach out to the team that owns that template and see if we can get it updated. Thank you!

**Comment by doiron** [comment]
duplciate issue [skill-sample-nodejs-hello-world/issues/43](https://github.com/alexa-samples/skill-sample-nodejs-hello-world/issues/43)  

thanks for creating an issue in the sample repo directly!
