### ISSUE TITLE
Remove withCustomerUserAgent() from index.js in Alexa-hosted skills template

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#420]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[X] Other... Please describe: Remove the call to `withCustomUserAgent()` from the lambda/index.js file in the Alexa-hosted skills template.

## Expected Behavior
The `withCustomUserAgent()` call is optional and generally unnecessary (except for special circumstances, in which the developer can add it themselves). In the interest of simplifying the template, this should not be in the template.

## Current Behavior
(see above)

## Steps to Reproduce (for bugs)
Use `ask new` to create a new Node.js, Alexa-hosted skills project. Observe that in lambda/index.js there is a call to `withCustomUserAgent()` near the end. 

## Possible Solution
Remove the call to `withCustomUserAgent()`.

## Your Environment and Context

* ask-cli version: 2.24.1
* Operating System and version: MacOS 11.6
* Node.js version used for development: 16.6.1
* NPM version used for development: 7.24.1

**Comment by CamdenFoucht** [comment]
Thank you for the suggestion, I will reach out to the team that owns that template to see if they will change it.

**Comment by doiron** [comment]
duplicate [skill-sample-nodejs-hello-world/issues/43](https://github.com/alexa-samples/skill-sample-nodejs-hello-world/issues/43)  

thanks for filing a issue on the sample skill repository itself.
