### ISSUE TITLE
Typo "porfile" 

### ISSUE THREAD

**Issue by bchoksi** [alexa/ask-cli#439]
https://github.com/alexa/ask-cli/blob/274e5e8d500cafef5533c3c27359aa29a6072f39/lib/builtins/deploy-delegates/lambda-deployer/index.js#L36

**Comment by CamdenFoucht** [comment]
Thank you for catching this! Will get it updated in next release 🙂

**Comment by doiron** [comment]
just released v2.29.1 with the fix. 

thanks again for reporting
