### ISSUE TITLE
Error on ask deploy

### ISSUE THREAD

**Issue by PabloLerma** [alexa/ask-cli#441]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior

`ask deploy` to configure AWS infra and deploy the skill

## Current Behavior

I'm getting an error running `ask deploy`

**CLI Snapshot**
<img width="561" alt="image" src="https://user-images.githubusercontent.com/871250/190020505-4357d3d4-e930-4399-a270-3ff1a223a682.png">

## Steps to Reproduce (for bugs)

- `ask new --template-url https://github.com/alexa-samples/skill-sample-nodejs-fact.git` - Default setup
- `cd lamdba & yarn install & cd ..`
- `ask deploy`

## Possible Solution

I don't know but `ask deploy` should prompt better error info or not error at all for basic Skill templates.

## Your Environment and Context

* ask-cli version: 2.28.0
* Operating System and version: macOS Monterrey 12.5.1
* Node.js version used for development: v15.12.0
* NPM version used for development: I use yarn 1.22.10

**Comment by doiron** [comment]
That seems to be an error reported back by the SMAPI service call.   Do you happen to see a Skill Id after running the last ask deploy command?  did it created a Skill in the Developer console portal?  You can also see your full list of skills by running ```ask smapi list-skills-for-vendor```

**Comment by PabloLerma** [comment]
Hey @doiron ! Thanks for helping!

Sadly no, the output that I get after running `ask deploy` is the same one as you can see on the screenshot, just `"message": "Required parameter(s) missing in the request."`

Running with `ask deploy --debug` I can see the following requests:
- `GET_NPM_REGISTRY`: 200 OK
- `CREATE-UPLOAD`: 200 OK
- `UPLOAD-SKILL-PACKAGE`: 200 OK
- `IMPORT-PACKAGE`: **400 Bad Request** (`POST https://api.amazonalexa.com/v1/skills/imports`)

Running `ask smapi list-skills-for-vendor` returns:
```
[Error]: {
  "message": "Required parameter vendorId was null or undefined when calling callListSkillsForVendorV1.",
  "stack": ...stacktrace...,
  "detail": {}
}
```

**Comment by PabloLerma** [comment]
Never mind, I had issues with `ask configure` and I thought I had it properly configured but I didn't sign in properly on AWS developer account hence I didn't have a venderId. Going to https://developer.amazon.com/mycid.html, configuring my  account and running `ask configure` again fixed `ask deploy`. Thanks!
