### ISSUE TITLE
How specify AWS region from ask cli?

### ISSUE THREAD

**Issue by france193** [alexa/ask-cli#442]
Hi! Is there any option available in the ask cli to specify the aws region in which there will be created the lambda function? 
I use the command: ask new -p <PROFILE_NAME>, but i can’t find any cli option to specify something like “--region eu-south-1”. I’d like to specify something different from the default: “us-east-1".

**Comment by tydonelson** [comment]
Hey @france193 , sorry for such a delay on this! 

Can you try changing the value of `awsRegion` in the skillInfrastructure section your ask-resources.json file? (or add the field if it's not there)

![image](https://user-images.githubusercontent.com/56455637/193119724-860cadb0-9f3a-4e7d-aa8f-a94072a74ad4.png)

**Comment by tydonelson** [comment]
There is some more documentation around the ask-resources.json file here: https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Alexa-Skill-Project-Definition.md#ask-resourcesjson-this-file-is-up-to-configure
