### ISSUE TITLE
ask run stopped working with 2.29.1

### ISSUE THREAD

**Issue by habuma** [alexa/ask-cli#455]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[ ] Other... Please describe: 
</code></pre>

## Expected Behavior

Up to and including v2.28.0, `ask run` would start up a local run of the skill, allowing me to test my skill without deploying it. 

## Current Behavior

After upgrading to v2.29.1, `ask run` emits only a line or two and then exits without error. Here is an example of what happens:

~~~
$ ask run --watch

*****Once the session is successfully started, you can use `ask dialog` to make simulation requests to your local skill code*****

Region chosen: NA
$
~~~

It does not start a local run.

Reverting back to v2.28.0 makes it work again.

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: 2.29.1
* MacOS 13.1
* Node.js v19.8.1
* NPM v9.6.4

**Comment by habuma** [comment]
Update: I didn't realize that when reverting back to 2.29.0, there is no such version and...for some reason...it was actually reverting back to 2.24.0. I've since tried this with 2.28.0 and it works as expected. It breaks starting with 2.29.1.

**Comment by doiron** [comment]
thanks for reporting the bug.  in the meantime, let us know if you are having any more issues reverting back to 2.28.0/ a working version.

**Comment by doiron** [comment]
this closed automatically,  still need to release a new version to npm

**Comment by doiron** [comment]
Just release ask-cli  v 2.29.2 that has a fix.   please give it a try and let us know if you are still running into issues with these new bits.

**Comment by habuma** [comment]
That seems to work! Thanks

**Comment by ktssr** [comment]
Not working in 2.29.2 also

**Comment by tydonelson** [comment]
hey @ktssr , are you seeing the original behavior that was reported here on 2.29.2, or some other error?

**Comment by doiron** [comment]
Also could you provide your env details?  This might help up get a repro on our side.


OS: ?
Node.js v?
NPM v?


thanks

**Comment by ktssr** [comment]
> hey @ktssr , are you seeing the original behavior that was reported here on 2.29.2, or some other error?

Yes Nothing is being displayed after this and the command prompt is stuck. ctrl + c is the only way out

*****Once the session is successfully started, you can use `ask dialog` to make simulation requests to your local skill code*****

Region chosen: NA
*****Starting Skill Debug Session***** 

*****Session will last for 1 hour*****

**Comment by ktssr** [comment]
> Also could you provide your env details? This might help up get a repro on our side.
> 
> OS: ? Node.js v? NPM v?
> 
> thanks

OS - Windows 10 64 bit
Node.js V - 18.15.0
NPM V - 9.5.0

**Comment by tydonelson** [comment]
Hey @ktssr , that is the correct behavior for `ask run`. It starts the debug session by opening a connection with the Alexa proxy service and then keeps the process open, listening for requests to the skill and re-routing them to your local lambda code. Those requests can be made via any source - the skill simulator in the developer console or ASK extension for VS Code, or via `ask dialog`. 

If you want to do skill simulation via `ask dialog`, I'd recommend just opening a second terminal. You could try running the `ask run` command as a background process to release text input in the same terminal, but it becomes easy to lose track of the `ask run` process and more difficult to terminate it.

**Comment by ktssr** [comment]
Thanks for clarifying @tydonelson. It's working as expected
