### ISSUE TITLE
use https for npmjs.org endpoint

### ISSUE THREAD

**Issue by doiron** [alexa/ask-cli#493]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request 
[X] Other... Please describe: 
- avoid a 302 HTTP to HTTPS redirection
</code></pre>

https://github.com/alexa/ask-cli/blob/12c0f97afe9150e66b681aa005160e6d2fcad886/lib/utils/constants.js#L4

## Expected Behavior

endpoint should be https 

## Current Behavior

currently http

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by jsetton** [comment]
It looks like #411 was reverted with the 2.29 merge.
