### ISSUE TITLE
Add building instructions for contributors

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#53]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Ideally the project directory [docs](https://github.com/alexa-labs/ask-cli/tree/master/docs) would include a simple MD file that explains how to build the project locally to test contributed improvements, bug fixes, new features, etc before submitting a PR.
As a bonus this file would contain any other useful instructions or pointers for developer trying to contribute to the project rather than just use it.
The top level readme file focuses on users, not contributors.

## Current Behavior

No instructions provided.

**CLI Snapshot**

## Possible Solution

Create a new MD file for this

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
Hi @germanviscuso ,

This is a good call, thanks for letting us know. It is in our plan to provide a contributing guide. We will let you know once it's ready through this thread.

Best,
Ron

**Comment by kakhaUrigashvili** [comment]
In PR https://github.com/alexa/ask-cli/pull/296
