### ISSUE TITLE
BREAKING CHANGE if you have used our public beta ask-cli-x

### ISSUE THREAD

**Issue by RonWang** [alexa/ask-cli#74]
### If you haven't managed your Alexa skill using `ask-cli-x` ([our beta program](https://www.npmjs.com/package/ask-cli-x)), you are not impacted by this. Please stop reading here.

Dear Alexa skill developers,

Thank you for using ask-cli-x, the beta version of ask-cli. Hope you have really enjoyed using it so far! 

The v0.11.0 release will be a small breaking change to the Alexa skill project structure that `ask-cli-x` supports. 

We will move all the CLI's cached data along with your resources' IDs into .ask/ask-states.json. The **.ask/** folder under your skill project will be served as the folder to track ask-cli-x's states values.

More explicit information about this change:

| field from old ask-resources.json       | move to .ask/ask-states.json (> v0.11.0)                          |
|----------------------------------------------------|-------------------------------------------------------------------|
| profiles.{profile}.skillId                         | profiles.{profile}.skillId                                        |
| profiles.{profile}.skillMetadata.lastDeployHash    | profiles.{profile}.skillMetadata.lastDeployHash                   |
| profiles.{profile}.code.{region}.lastDeployHash    | profiles.{profile}.code.{region}.lastDeployHash                   |
| profiles.{profile}.skillInfrastructure.deployState | profiles.{profile}.{deployerType}.skillInfrastructure.deployState |

---

For users who use version below v0.11.0, there are two methods you can take to upgrade the structure:
- If you want to keep the current skill project states values (i.e. your skillId and deployer's deployState), please change your skill project based on the table above.
- Run "askx init" to re-link your resources into the new version of the ask-resources.json. 
  - You will want to remember your skill-id, as the command wizard will ask you for the skillId.
  - You will also want to backup your `deployState` object, so that you won't need to re-create your AWS resources. To migrate this data, after the init command finishes, move the field by following the last row from the table above.

---

The reason for this change is: we've noticed that the ask-resources.json keeps changing whenever deploy happens. Those change will potentially influence your git user experiences if you track ask-resources.json file in your git. As an Alexa skill deployment tool, we recommend you including the ask-resources.json file into your git history as it stores how a project gets deployed.

Thanks for your understanding, please let us know anything that we can help for this migration.
ask-cli team

**Comment by germanviscuso** [comment]
When using `askx init` for migration the suggested directory for the back-end code is lambda while previous versions of askx used `code`. Is it going to be lambda by default for new projects from now on?

**Comment by germanviscuso** [comment]
This is going in the right direction with regards to encapsulating all deployment specific parameters inside the .ask directory (I saw that the lambda code with dependencies now goes there too). However there's something that breaks this which is that the lambda deployment uri is overwritten with the full uri path on `skill.json` after deploy. `skill.json` is the skill manifest, why should it contain deployment data? If you take a look at all the skill samples that we offer in github.com/alexa in `skill.json` we only specify the `sourceDir` (eg lambda) and the short function name as `uri` (eg. skill-demo-xxx) and the CLI v1 accepts it and can work with it (the arn is taken from `.ask/config`)

**Comment by RonWang** [comment]
> When using `askx init` for migration the suggested directory for the back-end code is lambda while previous versions of askx used `code`. Is it going to be lambda by default for new projects from now on?

CLI's ask-resources.json doesn't require a fixed name for your Lambda code base. But since our skill templates are all for the usage of Lambda function, we change the name of the folder from `code` to `lambda`, for all the templates.

**Comment by RonWang** [comment]
Close this issue as it's been linked in our FAQ session https://github.com/alexa/ask-cli/pull/321
