### ISSUE TITLE
Document how to include new policies in the lambda IAM role on deployment

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#79]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It's very common that skill developers have to include extra policies on the lambda role besides AWSLambdaBasicExecutionRole (ej. DynamoDB). It would be nice to show the developer how to do this automatically while deploying skills with the new CLI and a CloudFormation deployment.

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
Hey @germanviscuso 

We recently updated our one of the initially supported templates: https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/ask-cli-x/infrastructure/cfn-deployer/skill-stack.yaml#L40

The IAM role is modified to support DynamoDB, and the DynamoDB resource is also managed in the CloudFormation. Is this what you are talking about?

**Comment by germanviscuso** [comment]
That exactly what I meant, thx a lot!!!!! Please close it
