### ISSUE TITLE
Deploy ISP products in isps directory to be compatible with CLI v1

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#80]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

In the previous ASK-CLI the In Skill Purchasing (ISP) products in the directory `isps` where deployed on `ask deploy` and there was also granular control to deploy them independently with `ask deploy -t isp`
We need equivalent functionality in askx

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
Hey @germanviscuso 

I think this one is duplicate with https://github.com/alexa/ask-cli/issues/82, I will mark it as close as well. As mentioned in the prior thread, we will gradually build the trust that skillPackage can handle all the managed resources smartly and efficiently.

Thanks,
Ron
