### ISSUE TITLE
Add more granular deployment types (manifest, lambda, models)

### ISSUE THREAD

**Issue by germanviscuso** [alexa/ask-cli#82]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Sometime skill developers need to try more granular deployment types, such as the voice interaction models only even if work was done elsewhere (eg. the lambda). Relying on automatic detection of changes does not allow for these scenario as anything that changes gets deployed.
This was available in the CLI v1.
For example modifying Task definitions in the skill infrastructure causes the whole skill to be deployed.

## Current Behavior

**CLI Snapshot**

## Your Environment and Context

* ask-cli version: x.x.x
* Operating System and version:
* Node.js version used for development:
* NPM version used for development:

**Comment by RonWang** [comment]
Hi @germanviscuso ,

Thank you for the feature request! As you may know we rely on [Alexa skill package](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-package-api-reference.html#skill-package) to deploy our Alexa skill metadata. The service is working hard to support the deployment of the changed resource(s) only, and the InteractionModel is already supported that way. CLI side is likely not having the control to manage a specific resource for skillMetadata. Using granular SMAPI command would be a better way to achieve it.

With consuming skill package, ask-cli-x also wants to help developers offload the management of a specific resource but treat it as a project. So we might not be able to support this as a feature to the deploy command. Do you think this might block your usage a lot? Please feel free let us know!

Thanks,
Ron

**Comment by germanviscuso** [comment]
It's not a blocker, it just related to productivity as some small changes trigger a full deployment which takes time. I suppose we can live with it!

**Comment by RonWang** [comment]
Yes, we will definitely have this feature in mind, and we want to hear from our developers to drive the correct decision. I will close this for now and hope developers can voice out their need!
