### ISSUE TITLE
How to get logs of Alexa Hosted skill

### ISSUE THREAD

**Issue by Nikhil-Wagh** [alexa/ask-cli#83]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
The only way to view AWS Cloudwatch logs is through [this](https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#logs). Is it possible to view logs from console, using [`ask lambda logs`](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#log-subcommand)?

## Current Behavior
Currently, I'll have to log into my console, go to my skill then click on code section and from there I'll have to click on AWS Cloudwatch logs. A long way to go. If that can be simplified, it would be great.

**Comment by RonWang** [comment]
Hey @Nikhil-Wagh ,

Thanks for your feature request, we will put this feature request into our backlog. Unfortunately, you might still need to go to the console for now to check your Cloudwatch log.

Meanwhile for whoever found this feature useful, please up-vote this feature. Thanks for your feedback in advance!

**Comment by RonWang** [comment]
Close this issue since it's inactive, but feel free to bring the issue up anytime in the future!
